### PR TITLE
`IgnoredReturnValue`: add option `returnValueTypes` to enable rule for particular types

### LINKED ISSUE #4640: Add rule to check if Flow collected
## Expected Behavior of the rule

```kotlin
val profileFlow: Flow<Profile> = ...

fun observeProfile() {
    profileFlow.onEach { ... } // FlowNotCollected: launchIn, collect or another function is not called
}

fun observeProfile(): Flow<ProfileUi>  {
    return profileFlow.onEach { ... } // Ok: Flow is not collected but returned from function
}
```

## Context

It would be nice to catch cases when flow is not collected because:
1. It is quite easy to forget to collect flow, or you can use `onEach` instead of `collect` by mistake.
2. Even if you never forget to collect flow you can mess with this issue after refactoring:
    Imagine you want to migrate some function from suspend to flow:
    ```diff
    -suspend fun refreshProfile() { ... }
    +fun refreshProfile(): Flow<RefreshState> { ... }
    ```
    After this change all methods used `refreshProfile` become broken because returned flow is not collected.

### PR DESCRIPTION
**Pull request by osipxd**
> @BraisGabin said:
> We could extend IgnoredReturnValue and make it receive a list of types from the configuration. The rule will flag any call to a function that returns one of those types if the returned is ignored.

This PR adds config option `returnValueTypes` (is this option name OK?) to make it possible to enable the rule for functions returning specified types.
Also, I've added `kotlinx.coroutines.flow.Flow` to the default config.

Resolves #4640

### CODE REVIEW

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt [hunk 1]
```diff
@@ -61,6 +64,11 @@ class IgnoredReturnValue(config: Config = Config.empty) : Rule(config) {
         it.map(String::simplePatternToRegex)
     }
 
+    @Configuration("List of return types that should not be ignored")
+    private val returnValueTypes: List<Regex> by config(listOf("kotlinx.coroutines.flow.Flow")) {
```
Comment (osipxd) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:68]: Is these name and description are good?

File: detekt-test/src/main/kotlin/io/gitlab/arturbosch/detekt/test/FindingsAssertions.kt [hunk 2]
```diff
@@ -92,6 +92,15 @@ class FindingsAssert(actual: List<Finding>) :
 }
 
 class FindingAssert(val actual: Finding?) : AbstractAssert<FindingAssert, Finding>(actual, FindingAssert::class.java) {
+
+    fun hasSourceLocation(line: Int, column: Int) = apply {
```
Comment (osipxd) [inline detekt-test/src/main/kotlin/io/gitlab/arturbosch/detekt/test/FindingsAssertions.kt:96]: I've added this function to make it possible to use this assert in asserts chain:
```kotlin
assertThat(findings)
    .singleElement()
    .hasSourceLocation(line = 5, column = 10)
    .hasMessage("The call onEach is returning a value that is ignored.")
```
instead of
```kotlin
assertThat(findings).singleElement()
assertThat(findings).hasSourceLocation(line = 5, column = 10)
assertThat(findings.first()).hasMessage("The call onEach is returning a value that is ignored.")
```

File: detekt-rules-errorprone/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValueSpec.kt [hunk 3]
```diff
@@ -881,4 +881,70 @@ class IgnoredReturnValueSpec(private val env: KotlinCoreEnvironment) {
             assertThat(findings).isEmpty()
         }
     }
+
+    @Nested
+    inner class `return value types default config` {
```
Comment (osipxd) [inline detekt-rules-errorprone/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValueSpec.kt:886]: Should I add more tests?

**Comment by cortinico** [comment]
By looking at this rule API, I think we should add also the `restrictToReturnValueTypes` boolean config.

```
  IgnoredReturnValue
    active: true
    restrictToAnnotatedMethods: true
    returnValueAnnotations:
      - '*.CheckResult'
      - '*.CheckReturnValue'
    ignoreReturnValueAnnotations:
      - '*.CanIgnoreReturnValue'
+   restrictToReturnValueTypes: true
+   returnValueTypes:
+     - 'kotlinx.coroutines.flow.Flow'
```

The rule should then check if `restrictToReturnValueTypes` is true and the returned type is one of the listed -> Then report.

It makes for a more explicit configuration and it aligns to `restrictToAnnotatedMethods`/`returnValueAnnotations`

**Comment by osipxd** [comment]
> By looking at this rule API, I think we should add also the `restrictToReturnValueTypes` boolean config.
> The rule should then check if `restrictToReturnValueTypes` is true and the returned type is one of the listed -> Then report.
> 
> It makes for a more explicit configuration and it aligns to `restrictToAnnotatedMethods`/`returnValueAnnotations`

Thank you for API review!
Yes, i thought about it, but prefix `restrictTo` implies "exclusiveness" isn't it? In my mind `restrictToAnnotatedMethods` means "this rule will check only methods annotated with the specified annotations", and `restrictToReturnValueTypes` means "this rule will check only menthods returning the specified types", so it may be confusing if both of these flags are `true`.
But maybe it is only my feeling because of language barrier.

**Comment by cortinico** [comment]
> Yes, i thought about it, but prefix `restrictTo` implies "exclusiveness" isn't it? In my mind `restrictToAnnotatedMethods` means "this rule will check only methods annotated with the specified annotations", and `restrictToReturnValueTypes` means "this rule will check only menthods returning the specified types", so it may be confusing if both of these flags are `true`.

Yes that's correct. If enabled, the rule will flag only function which are returning the values types you listed. If this is not the case, then I misunderstood what was the semantic of your change.

**Comment by osipxd** [comment]
> Yes that's correct. If enabled, the rule will flag only function which are returning the values types you listed. If this is not the case, then I misunderstood what was the semantic of your change.

I mean sentence _"rule will check **only** annotated methods"_ conflicts with _"rule will check **only** methods returning the specified types"_ because both contain word "only". So maybe there may be better naming? Something that means _"always check methods returning specified types even if checks enabled only for annotated methods"_?

**Comment by cortinico** [comment]
> So maybe there may be better naming? Something that means _"always check methods returning specified types even if checks enabled only for annotated methods"_?

I would suggest to don't implement this logic. The two `restrict` should apply on top of each other and further restrict the set of return values we inspect. What you're suggesting instead seems harder to explain and understand for users IMHO

**Comment by BraisGabin** [comment]
🤔 I think that we should reframe the configuration of this rule. To me this issue should flag a function if it returns a `Flow` (or any other class listed on the configuration) or if it is annotated with some of the listed annotations. Then, we should have another flag that would ignore all those configurations and will flag all the cases where the return value is not `Unit` nor `Nothing`. Do that have sense? 

To do that I would deprecate the current boolean flag and rename it to some naming more clear.

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt [hunk 4]
```diff
@@ -49,8 +54,14 @@ class IgnoredReturnValue(config: Config = Config.empty) : Rule(config) {
     )
 
     @Configuration("if the rule should check only annotated methods")
+    @Deprecated("Use `restrictToConfig` instead")
     private val restrictToAnnotatedMethods: Boolean by config(defaultValue = true)
 
+    @Suppress("DEPRECATION")
+    @OptIn(UnstableApi::class)
+    @Configuration("If the rule should check only methods matching to configuration, or all methods")
+    private val restrictToConfig: Boolean by configWithFallback(::restrictToAnnotatedMethods, defaultValue = true)
```
Comment (osipxd) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:63]: The best name that I came up with. Is there any better variants?

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt [hunk 5]
```diff
@@ -61,6 +72,15 @@ class IgnoredReturnValue(config: Config = Config.empty) : Rule(config) {
         it.map(String::simplePatternToRegex)
     }
 
+    @Configuration("List of return types that should not be ignored")
+    private val returnValueTypes: List<Regex> by config(
+        listOf(
+            "kotlin.sequences.Sequence",
+            "kotlinx.coroutines.flow.*Flow",
+            "java.util.stream.*Stream",
```
Comment (osipxd) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:80]: Is it OK to add java Streams here or should I keep only Kotlin types?

Comment (osipxd) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:80]: Is it OK to add java Streams here or should I keep only Kotlin types?

**Review by osipxd — COMMENTED** [review]
@cortinico, @BraisGabin, I've just updated this PR, can you take a look?

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt [hunk 6]
```diff
@@ -86,7 +106,8 @@ class IgnoredReturnValue(config: Config = Config.empty) : Rule(config) {
 
         val annotations = resultingDescriptor.annotations
         if (annotations.any { it in ignoreReturnValueAnnotations }) return
-        if (restrictToAnnotatedMethods &&
+        if (restrictToConfig &&
+            resultingDescriptor.returnType !in returnValueTypes &&
```
Comment (cortinico) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:110]: Can we keep the older behavior in some form (i.e. check for `restrictToAnnotatedMethods` in another if condition as well)?

Comment (osipxd) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:110]: But `restrictToAnnotatedMethods` will always equal to `restrictToConfig`, isn't it? Maybe I don't quite understand what you mean.

Comment (cortinico) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:110]: Never mind. I realized that you marked `restrictToAnnotatedMethods` as deprecated so it won't be possible for users to use it, they'll be warned to migrate to the new property.

Without that, we could have had users with `restrictToAnnotatedMethods` set to true, in the next version of Detekt. For such users, you would have had to add some backward compatibility logic.

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt (hunk 5 above)
Comment (BraisGabin) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:80]: It's ok for me. We can always remove it later if we end up thinking of "java" as a "framework".

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt (hunk 4 above)
Comment (BraisGabin) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:63]: Naming is so difficult. I think your naming is good. I'm just proposing other but I'm not sure if it's better. What do you think?

```suggestion
    @Suppress("DEPRECATION")
    @OptIn(UnstableApi::class)
    @Configuration("If the rule should check all methods ignoring the annotations or return types.")
    private val checkAllMethods: Boolean by configWithFallback({ !restrictToAnnotatedMethods }, defaultValue = true)
```

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt (hunk 4 above)
Comment (osipxd) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:63]: Yes that's better

Comment (osipxd) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt:63]: But when I try to do it, I get the error:
image

The options I see:
1. Add the new parameter to `configWithFallback` that will transform fallback value
2. Keep the new property equal to `restrictToAnnotatedMethods`

**Review by BraisGabin — APPROVED** [review]

**Comment by osipxd** [comment]
Sorry for ping, but should it be merged?

File: detekt-core/src/main/resources/default-detekt-config.yml [hunk 7]
```diff
@@ -431,12 +431,16 @@ potential-bugs:
     active: true
   IgnoredReturnValue:
     active: true
-    restrictToAnnotatedMethods: true
```
Comment (cortinico) [inline detekt-core/src/main/resources/default-detekt-config.yml:434]: Reminder for self: this should be noted in the release notes

**Review by cortinico — APPROVED** [review]
I'm fine with merging this 👍

**Comment by BraisGabin** [comment]
Thank you for the PR :)

File: detekt-core/src/main/resources/default-detekt-config.yml (hunk 7 above)
Comment (osipxd) [reply detekt-core/src/main/resources/default-detekt-config.yml:434]: @cortinico this change was not mentioned in release notes 🙈

Comment (cortinico) [reply detekt-core/src/main/resources/default-detekt-config.yml:434]: Thanks for the reminder 👍
