### PR TITLE
UseDataClass: fix false positive on value classes

### LINKED ISSUE #4010: UseDataClass triggers on value classes
## Expected Behavior

Detekt does not report "UseDataClass" on value classes.

## Observed Behavior

Detekt reports "UseDataClass" on value classes.

## Steps to Reproduce

```kotlin
@JvmInline
value class PlayerId(val value: Long)
```

## Context

Kotlin 1.5 renamed `inline class` to `value class`. The former was handled in #1450 but the latter is the stable feature.

## Your Environment

* Version of detekt used: 1.17.1
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by cortinico**
Fixes #4010

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt [hunk 1]
```diff
@@ -326,6 +326,14 @@ class UseDataClassSpec : Spek({
             assertThat(subject.lint("inline class A(val x: Int)")).isEmpty()
         }
 
+        it("does not report value classes") {
+            val code = """
+                @JvmInline
+                value class PlayerId(val value: Long)
```
Comment (dlin-ta) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt:332]: Not that it should make a difference but it looks like other tests in this file use simpler names and types.
```kotlin
class A(val x: Int)
```

**Review by dlin-ta — APPROVED** [review]

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt (hunk 1 above)
Comment (schalkms) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt:332]: +1

**Review by schalkms — APPROVED** [review]

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt (hunk 1 above)
Comment (cortinico) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UseDataClassSpec.kt]: Makes sense, updated.

**Review by marschwar — APPROVED** [review]
