### PR TITLE
ClassNaming: Don't treat Kotlin syntax ` as part of class name

### LINKED ISSUE #2656: ClassNaming rule treating Kotlin syntax ` as part of class name
## Expected Behavior
ClassNaming rule should only check class name and should not check syntax \`

## Observed Behavior
ClassNaming rule treating Kotlin syntax \` as part of class name

## Steps to Reproduce
```Kotlin
class `$Test$`
```
The above code is warned about a ClassNaming issue with default config 
```
  ClassNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
```
When I change the classPattern to ``[`A-Z$][`a-zA-Z0-9$]*``, the warning is gone.
This means detekt is treating the syntax ` as part of class name, which is probably not intended.

## Context
Class names with $ in it should pass the test, otherwise you would not write it to the default pattern. But it's not possible to have such a class name without the \` syntax.

## Your Environment

* Version of detekt used: 1.8.0
* Version of Gradle used (if applicable): 5.6.4
* Operating System and version: macOS Catalina
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by BraisGabin**
This tries to fix #2656. But I find this a bit controversial:

Pros:

- It's true that `` ` ``  is not part of the name of a class (or any other entity in the code).

Cons:

- `FunctionNaming` is using this "error" to provide the feature that only allows any type of function name if it uses backticks. That's like that because in the tests we want to allow that kind of naming in the functions.

I vote to merge because I think that the one that is wrong is `FunctionNaming`. But fixing `FuctionNaming` is not easy. A way to fix it would be to allow multiple instances of the same rule with different configurations. This way we could have an instance that checks FunctionNaming in production code and another for test code.

Maybe a solution is to exclude `FunctionNaming` from test source sets and don't allow backtick at all.

### CODE REVIEW

File: detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/ClassNaming.kt [hunk 1]
```diff
@@ -47,3 +47,11 @@ class ClassNaming(config: Config = Config.empty) : Rule(config) {
         const val CLASS_PATTERN = "classPattern"
     }
 }
+
+private fun String.cleanBackticks(): String {
```
Comment (chao2zhang) [inline detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/ClassNaming.kt:51]: We could simplify use `String.removeSurrounding("`")`

**Review by chao2zhang — APPROVED** [review]

File: detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/ClassNaming.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/ClassNaming.kt]: Didn't know abot that one! Thanks!

**Review by cortinico — APPROVED** [review]
