### PR TITLE
Dynamically insert the version into ktlint rule links

### LINKED ISSUE #6602: `<ktlintVersion/>` substitution in docs is broken
## Expected Behavior
https://detekt.dev/docs/rules/formatting links point to existing pages.

## Observed Behavior
All links in https://detekt.dev/docs/rules/formatting are missing the version number from the path in the URL:
image
For detekt docs version 1.23.3.

## Context
I diffed #6575 changes.

## Your Environment

* Version of detekt used: 1.23.3
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by marschwar**
Fixes #6602 

This backports the automatic ktlint version replacement to the 1.x branch to (hopefully) fix the documentation generation for future 1.x releases. I also copied the versioned docs from the main branch.

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/IfElseBracing.kt [hunk 1]
```diff
@@ -10,7 +10,7 @@ import io.gitlab.arturbosch.detekt.api.internal.Configuration
 import io.gitlab.arturbosch.detekt.formatting.FormattingRule
 
 /**
- * See [ktlint docs](https://pinterest.github.io/ktlint/rules/experimental/#if-else-bracing) for documentation.
+ * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/experimental/#if-else-bracing) for documentation.
```
Comment (chao2zhang) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/IfElseBracing.kt:13]: What do we think about just putting a generic link to Ktlint rules?

1. https://pinterest.github.io/ktlint/1.0.1/rules/experimental/#if-else-bracing won't work because this was promoted from experimental to standard - https://pinterest.github.io/ktlint/1.0.1/rules/standard/#if-else-bracing is the right link
2. It is such a chore to always remember updating with the documentation link (We could also use integration test to actually verified HTTP response status = 200)

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/PackageName.kt [hunk 2]
```diff
@@ -7,7 +7,7 @@ import io.gitlab.arturbosch.detekt.api.internal.AutoCorrectable
 import io.gitlab.arturbosch.detekt.formatting.FormattingRule
 
 /**
- * See [ktlint docs](https://pinterest.github.io/ktlint/rules/standard/#no-underscores-in-package-names) for
+ * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/#no-underscores-in-package-names) for
```
Comment (TWiStErRob) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/PackageName.kt:10]: https://pinterest.github.io/ktlint/0.47.0/rules/standard/#no-underscores-in-package-names
https://pinterest.github.io/ktlint/0.48.0/rules/standard/#package-name
https://pinterest.github.io/ktlint/0.49.0/rules/standard/#package-name
https://pinterest.github.io/ktlint/0.50.0/rules/standard/#package-name
```suggestion
 * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/#package-name) for
```

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/TrailingCommaOnCallSite.kt [hunk 3]
```diff
@@ -9,7 +9,7 @@ import io.gitlab.arturbosch.detekt.api.internal.Configuration
 import io.gitlab.arturbosch.detekt.formatting.FormattingRule
 
 /**
- * See [ktlint docs](https://pinterest.github.io/ktlint/rules/standard/) for documentation.
+ * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/) for documentation.
```
Comment (TWiStErRob) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/TrailingCommaOnCallSite.kt:12]:
```suggestion
 * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/#trailing-comma-on-call-site) for documentation.
```

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/TrailingCommaOnDeclarationSite.kt [hunk 4]
```diff
@@ -9,7 +9,7 @@ import io.gitlab.arturbosch.detekt.api.internal.Configuration
 import io.gitlab.arturbosch.detekt.formatting.FormattingRule
 
 /**
- * See [ktlint docs](https://pinterest.github.io/ktlint/rules/standard/) for documentation.
+ * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/) for documentation.
```
Comment (TWiStErRob) [inline detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/TrailingCommaOnDeclarationSite.kt:12]:
```suggestion
 * See [ktlint docs](https://pinterest.github.io/ktlint/<ktlintVersion/>/rules/standard/#trailing-comma-on-declaration-site) for documentation.
```

File: detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/IfElseBracing.kt (hunk 1 above)
Comment (TWiStErRob) [reply detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/IfElseBracing.kt:13]: > What do we think about just putting a generic link to Ktlint rules?

From me that would be a hard no, because the point of these links is that you can see the documentation of the rule that you're looking at (assuming the link works 😅). Without the link these wrapper rules would have no documentation at all. If we link to "KtLint homepage" or "standard rules", at that point there's no point linking at all, because we push the chore of navigating the website to our users.

It should be part of the version bump to ensure all links work, like this: https://github.com/detekt/detekt/pull/6298#pullrequestreview-1543220279 (If you look at the timestamps of the comments, it took me 10 minutes to validate all links, and it was that much because there were a lot broken.) I just did the same exercise on this for [0.50.0](https://github.com/marschwar/detekt/blob/fix/6602_fix_links/gradle/libs.versions.toml#L5). And it took 3 minutes to validate and 9 minutes to research broken ones.

I agree it could be automated, but it's probably not necessary, because the [release notes](https://github.com/pinterest/ktlint/releases) always clearly call out the promotions and demotions.

Although, in general I agree that all external (and maybe internal and fragment-navigation) links could be tested that way, but that's a separate improvement to ktlint bumps.

File: detekt-generator/build.gradle.kts [hunk 5]
```diff
@@ -74,6 +74,8 @@ val generateDocumentation by tasks.registering(JavaExec::class) {
         configDir,
         "--cli-options",
         cliOptionsFile,
+        "--replace",
+        "<ktlintVersion/>=${libs.versions.ktlint.get()}"
```
Comment (TWiStErRob) [inline detekt-generator/build.gradle.kts:78]: Once this PR is ready and merged, I think we need to run the website generation on `release/1.x` and overwrite the 1.23.3 docs on `main` so that the links are working at https://detekt.dev/docs/rules/formatting (latest stable is 1.23.3).

**Review by TWiStErRob — APPROVED** [review]

**Comment by marschwar** [comment]
Sorry for the delay.

**Review by cortinico — APPROVED** [review]
