### PR TITLE
UnnecessaryNotNullCheck: fix false negative with smart casted arguments

### LINKED ISSUE #5379: UnnecessaryNotNullCheck: false negative with smart casted arguments
## Steps to Reproduce
```kotlin
 @Test
 fun shouldDetectAfterNullCheck() {
     val code = """
         fun foo(x: Int?) {
             if (x != null) {
                 requireNotNull(x)
             }
         }
     """.trimIndent()
     val findings = subject.lintWithContext(env, code)
     assertThat(findings).hasSize(1)
 }

 @Test
 fun shouldDetectAfterTypeCheck() {
     val code = """
         fun bar(x: Any?) {
             if (x is String) {
                 requireNotNull(x)
             }
         }
     """.trimIndent()
     val findings = subject.lintWithContext(env, code)
     assertThat(findings).hasSize(1)
 }
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #5379

### CODE REVIEW

File: detekt-psi-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/TypeUtils.kt [hunk 1]
```diff
@@ -1,10 +1,41 @@
...
 import org.jetbrains.kotlin.types.KotlinType
 import org.jetbrains.kotlin.types.TypeUtils
+import org.jetbrains.kotlin.util.containingNonLocalDeclaration
 
 fun KotlinType.fqNameOrNull(): FqName? {
     return TypeUtils.getClassDescriptor(this)?.fqNameOrNull()
 }
+
+@Suppress("ReturnCount")
+fun KtExpression.getDataFlowAwareTypes(
```
Comment (cortinico) [inline detekt-psi-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/TypeUtils.kt:18]: Can we add a comment on this function with a couple of example of what it does?

**Review by cortinico — APPROVED** [review]
Great stuff!

**Review by BraisGabin — APPROVED** [review]

File: detekt-psi-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/TypeUtils.kt (hunk 1 above)
Comment (t-kameyama) [reply detekt-psi-utils/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/TypeUtils.kt:31]: [3cdd9ac](https://github.com/detekt/detekt/pull/5380/commits/3cdd9ac6347befa3c3b40d440d1cba313132ab9c)

**Review by chao2zhang — APPROVED** [review]
