### PR TITLE
Ensure SourceSet-based tasks are registered once

### LINKED ISSUE #8613: detekt gradle plugin creates the same task multiple times
## Expected Behavior
I can apply the detekt gradle plugin to my project

## Observed Behavior
I can't! I get this message:

```
An exception occurred applying plugin request [id: 'common-android-feature']
> Failed to apply plugin class 'dev.detekt.gradle.plugin.DetektBasePlugin'.
   > Cannot add task 'detektAndroidTestSourceSet' as a task with that name already exists.
```

The stack trace is:
```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'detektAndroidTestSourceSet' as a task with that name already exists.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:262)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.registerTask(DefaultTaskContainer.java:416)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.register(DefaultTaskContainer.java:393)
        at dev.detekt.gradle.plugin.DetektBasePlugin$registerSourceSetTasks$1$1.invoke(DetektBasePlugin.kt:80)
        at dev.detekt.gradle.plugin.DetektBasePlugin$registerSourceSetTasks$1$1.invoke(DetektBasePlugin.kt:78)
        at dev.detekt.gradle.plugin.DetektBasePlugin$registerSourceSetTasks$1.invoke$lambda$0(DetektBasePlugin.kt:78)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:109)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:106)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)
        at dev.detekt.gradle.plugin.DetektBasePlugin$registerSourceSetTasks$1.invoke(DetektBasePlugin.kt:78)
        at dev.detekt.gradle.plugin.DetektBasePlugin$registerSourceSetTasks$1.invoke(DetektBasePlugin.kt:75)
        at dev.detekt.gradle.plugin.DetektBasePlugin.registerSourceSetTasks$lambda$2(DetektBasePlugin.kt:75)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:109)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:106)
        at org.gradle.api.internal.collections.CollectionFilter$1.execute(CollectionFilter.java:61)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:227)
        at dev.detekt.gradle.plugin.DetektBasePlugin.registerSourceSetTasks(DetektBasePlugin.kt:75)
        at dev.detekt.gradle.plugin.DetektBasePlugin.apply(DetektBasePlugin.kt:66)
        at dev.detekt.gradle.plugin.DetektBasePlugin.apply(DetektBasePlugin.kt:21)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:55)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
        ... 234 more
```

## Steps to Reproduce
Migrate to detekt 2.0 and execute `./gradlew tasks` for example.

## Context
I was trying to migrate from detekt 1.0 to 2.0

I checked that in my project this code:

https://github.com/detekt/detekt/blob/d6951dd657b477fa5541f9c3723ff0a238d13313/detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt#L75-L78

is called multiple times with `sourceSets` with the same name. I saw modules with 2 repetitions and others with 3. Right now I don't know what's creating this behavior and why this doesn't happen on our tests.

## Your Environment
* Version of detekt used: 2.0.0-alpha.0
* Version of Gradle used (if applicable): 9.0.0
* Operating System and version: mac

### PR DESCRIPTION
**Pull request by 3flex**
Should fix #8613 

We don't need to worry about threading since configuration is single threaded within a given project, but this could be made an AtomicBoolean if there are concerns.

### CODE REVIEW

**Review by BraisGabin — COMMENTED** [review]
Should we add a test to avoid regression?

File: detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt [hunk 1]
```diff
@@ -73,6 +75,10 @@ class DetektBasePlugin : Plugin<Project> {
 
     private fun Project.registerSourceSetTasks(extension: DetektExtension) {
         project.plugins.withType(KotlinBasePlugin::class.java) {
+            if (sourceSetListenerConfigured) return@withType
```
Comment (BraisGabin) [inline detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt:78]: I would move this to the call site of `registerSourceSetTasks`. Or rename the function to something like `registerSourceSetTasksIfNeeded` and move the `if` outside the `withType`.

File: detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt [hunk 2]
```diff
@@ -19,6 +19,8 @@ import org.jetbrains.kotlin.gradle.plugin.KotlinBasePlugin
 import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSetContainer
 
 class DetektBasePlugin : Plugin<Project> {
+    var sourceSetListenerConfigured = false
```
Comment (BraisGabin) [inline detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt]:
```suggestion
    private var sourceSetListenerConfigured = false
```

File: detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt (hunk 1 above)
Comment (3flex) [reply detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt:78]: `withType` is live though so the action will be called multiple times if there are multiple matching plugins with that type, so I don't think we can move the `if` outside? Or am I missing something?

Comment (BraisGabin) [reply detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt:78]: You are right! My bad.

**Comment by 3flex** [comment]
> Should we add a test to avoid regression?

Done - triggers the issue on `main` as expected.
