### PR TITLE
`jcenter()` -> `mavenCentral()`

### LINKED ISSUE #3461: Upgrade to 0.7.2 of kotlinx-html-jvm
## Expected Behavior
Can build without Jcenter which is going away soon. Use mavenCentral only.

## Observed Behavior
```
  > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.1.
     Required by:
         project :ocr > io.gitlab.arturbosch.detekt:detekt-cli:1.7.4
```

## Steps to Reproduce
Run the detekt Gradle task.

## Context
0.7.2 is published but not 0.7.1: https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-jvm?repo=kotlinx

### PR DESCRIPTION
**Pull request by cortinico**
This is a tentative PR to remove our dependency on `jcenter()`.

The impact on our project is:
- We're currently depending on kotlix-html that hasn't been migrated to JCenter yet (see https://github.com/Kotlin/kotlinx.html/issues/81 & https://github.com/Kotlin/kotlinx.html/issues/173)
- We have several older versions of Detekt on JCenter that haven't been migrated to Central yet.

I'll keep this PR updated as things evolve.

Fixes #3461

### CODE REVIEW

**Comment by ber4444** [comment]
This PR is incorrect, as they do not seem to be moving to `mavenCentral`, instead they use their own JetBrains repo, see https://github.com/detekt/detekt/issues/3642

**Comment by IRus** [comment]
> This PR is incorrect, as they do not seem to be moving to `mavenCentral`, instead they use their own JetBrains repo, see #3642

There are no evidence that it's true. kotlinx.html will be defenitly presented in mavenCentral, you can track that issue: https://github.com/Kotlin/kotlinx.html/issues/173

**Comment by smyrick** [comment]
We could migrate to pull the dependency from JetBrains Space

https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-806910768

**Comment by BraisGabin** [comment]
> We could migrate to pull the dependency from JetBrains Space as an alternative
> 
> [Kotlin/kotlinx.html#173 (comment)](https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-806910768)

What do we get from that? JetBrains will move this to mavenCental. And jCenter will be up for nearly one year. If someone is in a hurry to remove jcenter they can do it. But I don't think that we should promote the JetBrains repository. They are not promoting it so I don't see the point for us to promote it.

As I said, if someone is in a hurry to remove jCenter can use the JetBrains repository but I think that we should wait.

**Comment by dsvensson** [comment]
kotlinx.html is on central now, https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-826522662

**Comment by BraisGabin** [comment]
I didn't realiced that this one was already a PR. And I did it again: https://github.com/detekt/detekt/compare/main...remove-jcenter

My branch is a bit more aggresive. No idea if that's ok or not. But I think that this changes should be done: https://github.com/detekt/detekt/commit/37fcead29beb5060a600db26c702b57426f79a27

**Comment by G00fY2** [comment]
[kotlinx.html 0.7.3 is available in mavenCentral](https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-826522662)

**Comment by hsz** [comment]
Please note that v0.7.2 was **not published** to MC – just the newest release, **v0.7.3**.

**Comment by cortinico** [comment]
> I didn't realiced that this one was already a PR. And I did it again: [main...remove-jcenter](https://github.com/detekt/detekt/compare/main...remove-jcenter)
> My branch is a bit more aggresive. No idea if that's ok or not. But I think that this changes should be done: [37fcead](https://github.com/detekt/detekt/commit/37fcead29beb5060a600db26c702b57426f79a27)

Rebased and included your changes 👌

**Comment by dsvensson** [comment]
@cortinico Shouldn't you also bump to 0.7.3 in detekt-bom?

**Comment by cortinico** [comment]
> @cortinico Shouldn't you also bump to 0.7.3 in detekt-bom?

Yup you're right :)

**Comment by chao2zhang** [comment]
We probably need to bump to the latest version of dokka to avoid pulling `kotlinx.html:0.7.2`

https://gist.github.com/chao2zhang/6522db3677cbd3799ad70596d2f51779

**Review by BraisGabin — APPROVED** [review]

File: detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektJvmTest.kt [hunk 1]
```diff
@@ -22,8 +22,8 @@ object DetektJvmTest : Spek({
 
                 repositories {
                     mavenCentral()
-                    jcenter()
                     mavenLocal()
+                    jcenter()
```
Comment (chao2zhang) [inline detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektJvmTest.kt:26]: Once we publish the new version, we should be able to remove these references in our gradle integration test.

**Review by chao2zhang — APPROVED** [review]

**Comment by dsvensson** [comment]
What timeframe do you see for this to be a part of a release?

**Comment by BraisGabin** [comment]
I would say "soon" but that's completely subjective. There is not ETA but we know that this is something that a lot of users are wating for so we will try to create a new version "soon".

**Comment by cortinico** [comment]
1.17.0-RC1 is out and includes this change https://github.com/detekt/detekt/releases/tag/v1.17.0-RC1
Please give it a try so we can release a production version asap 👍

**Comment by theexiile1305** [comment]
@cortinico 
I've tried the newest version `1.17.0-RC1` out like the following configuration in the `build.gradle.kts `
```
repositories {
    mavenCentral()
}

plugins {
    ...
    id("io.gitlab.arturbosch.detekt") version "1.17.0-RC1"
}
```

Unfortunately the plugin doesn't work as expected. The execution of `./gradlew detekt` produces the following error:
```
> Task :detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> Could not resolve all files for configuration ':detekt'.
   > Could not find io.gitlab.arturbosch.detekt:detekt-cli:1.17.0.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
