### PR TITLE
Respect `RunAfterRule` constraint from ktlint

### LINKED ISSUE #5259: detekt doesn't respect ktlint `RunAfterRule` constraints
## Expected Behavior
detekt runs ktlint rules in the order that ktlint expects.

## Observed Behavior
ktlint has a few different visitor modifiers that add constraints to the order rules are run in.

detekt checks and respects `RunAsLateAsPossible` and `RunOnRootNodeOnly` constraints, but does not check `RunAfterRule`. This can affect results when using autocorrect and individual rules aren't run in the correct order.

See https://github.com/pinterest/ktlint/blob/0.46.1/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/Rule.kt#L39-L60

## Steps to Reproduce
I don't have a reproducer, but discovered this when doing some other work on the formatting rule set.

## Context
Can affect autocorrect.

## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by chao2zhang**
Resolves #5259 

Consulted with ktlint in https://github.com/pinterest/ktlint/pull/2062, we are building a consistent sorting logic in detekt to match ktlint.

### CODE REVIEW

File: detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingProviderSpec.kt [hunk 1]
```diff
@@ -1,19 +1,47 @@
...
-    fun `preferred ktlint rule ordering is applied`() {
+    fun `list is unique`() {
         val subject: RuleSet = FormattingProvider().instance(Config.empty)
+        subject.rules.groupBy { it.ruleId }.forEach {
+            assertThat(it.value).hasSize(1)
+        }
+    }
 
+    @Test
+    fun `run as late as possible is observed`() {
```
Comment (chao2zhang) [inline detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingProviderSpec.kt:20]: Shall we disable the test until https://github.com/pinterest/ktlint/pull/2062 is merged and updated in detekt?

Comment (marschwar) [reply detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingProviderSpec.kt:20]: > The rule sorter first runs all rules without any VisitorModifier.
The next group of rules are the rules marked with RunAsLateAsPossible.
The last group are the rules marked with RunAfter.

Should we update this PR to emulate the same mechanics as ktlint.

**Review by BraisGabin — APPROVED** [review]

File: detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingProviderSpec.kt (hunk 1 above)
Comment (chao2zhang) [reply detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingProviderSpec.kt:20]: We are following the same logic in this PR, let me add some comments for posterity
