### PR TITLE
NamedArguments rule: fix false positive with trailing lambda

### LINKED ISSUE #3658: NamedArguments rule: false positive with trailing lambda
```kotlin
fun foo(a: Int, b: Int, c: Int, block: ((Int) -> Int)) {}

fun test() {
    foo(a = 1, b = 2, c = 3) { it }
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #3658

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt [hunk 1]
```diff
@@ -53,11 +54,13 @@ class NamedArguments(
         }
     }
 
+    @Suppress("ReturnCount")
     private fun KtCallExpression.canNameArguments(): Boolean {
+        val unnamedArguments = valueArguments.filter { !it.isNamed() && it !is KtLambdaArgument }
```
Comment (marschwar) [inline detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt:59]: Suggestion:
```kotlin
val unnamedArguments = valueArguments.dropWhile { it.isNamed() || it is KtLambdaArgument }
```

Comment (chao2zhang) [reply detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt:59]: Let me make it a formal suggestion and merge this pr.

Comment (chao2zhang) [inline detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt:59]:
```suggestion
        val unnamedArguments = valueArguments.dropWhile { it.isNamed() || it is KtLambdaArgument }
```

File: detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt [hunk 2]
```diff
@@ -56,7 +56,7 @@ class NamedArguments(
 
     @Suppress("ReturnCount")
     private fun KtCallExpression.canNameArguments(): Boolean {
-        val unnamedArguments = valueArguments.filter { !it.isNamed() && it !is KtLambdaArgument }
+        val unnamedArguments = valueArguments.dropWhile { it.isNamed() || it is KtLambdaArgument }
```
Comment (marschwar) [inline detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt:59]: I am really sorry. I know I suggested it in the first place, but we most likely want `filterNot` instead of  `dropWhile`

File: detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt [hunk 3]
```diff
@@ -53,11 +54,13 @@ class NamedArguments(
         }
     }
 
+    @Suppress("ReturnCount")
     private fun KtCallExpression.canNameArguments(): Boolean {
+        val unnamedArguments = valueArguments.dropWhile { it.isNamed() || it is KtLambdaArgument }
```
Comment (chao2zhang) [inline detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/NamedArguments.kt:59]:
```suggestion
        val unnamedArguments = valueArguments.filterNot { it.isNamed() || it is KtLambdaArgument }
```
