### PR TITLE
Fix ForbiddenComment rule not checking for KDoc

### LINKED ISSUE #3273: ForbiddenComments don't report TODO: in KDoc
## Expected Behavior

`TODO:` in KDoc should be reported.

## Observed Behavior

`TODO:` in KDoc not be reported.

## Steps to Reproduce

```kotlin
/**
 * TODO: this is not reported
 */
object Test {

    fun testFunc() {
        /**
         * TODO: this is not reported, too.
         */
    }
}
```

`detekt -r xml:result.xml -i Test.kt`

Nothing is reported in result.xml

## Your Environment

* Version of detekt used:  1.14.2 CLI
* Version of Gradle used (if applicable):
* Operating System and version: OSX 10.15.4
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by schalkms**
ForbiddenComment now analyzes KDoc elements for forbidden comments.
KDoc sections don't inherit from the PsiComment type.
Hence, this rule needs to also gather and analyze KDocSection types.

Fixes #3273

### CODE REVIEW

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt [hunk 1]
```diff
@@ -40,15 +37,29 @@ class ForbiddenComment(config: Config = Config.empty) : Rule(config) {
...
     override fun visitComment(comment: PsiComment) {
         super.visitComment(comment)
-
         val text = comment.text
+        checkForbiddenComment(text, comment)
+    }
+
+    override fun visitKtFile(file: KtFile) {
+        super.visitKtFile(file)
+        file.collectDescendantsOfType<KDocSection>().forEach { comment ->
```
Comment (arturbosch) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:46]: Are there `visit` methods for `KDocSection`?
If yes would this be cleaner than writing a multiline lambda?

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt [hunk 2]
```diff
@@ -40,15 +37,29 @@ class ForbiddenComment(config: Config = Config.empty) : Rule(config) {
...
+    private fun checkForbiddenComment(text: String, comment: PsiElement) {
         if (allowedPatterns.pattern.isNotEmpty() && allowedPatterns.containsMatchIn(text)) return
 
         values.forEach {
             if (text.contains(it, ignoreCase = true)) {
-                report(CodeSmell(issue, Entity.from(comment), "This comment contains text that has been " +
-                        "defined as forbidden in detekt."))
+                report(
+                    CodeSmell(
+                        issue, Entity.from(comment), "This comment contains text that has been " +
```
Comment (arturbosch) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:59]: Would splitting a parameter per line remove the need for the string concatenation?

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt [hunk 3]
```diff
@@ -1,15 +1,12 @@
...
 
-import io.gitlab.arturbosch.detekt.api.CodeSmell
-import io.gitlab.arturbosch.detekt.api.Config
-import io.gitlab.arturbosch.detekt.api.Debt
-import io.gitlab.arturbosch.detekt.api.Entity
-import io.gitlab.arturbosch.detekt.api.Issue
-import io.gitlab.arturbosch.detekt.api.LazyRegex
-import io.gitlab.arturbosch.detekt.api.Rule
-import io.gitlab.arturbosch.detekt.api.Severity
+import io.gitlab.arturbosch.detekt.api.*
```
Comment (arturbosch) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt]: This line may lead to CI failure :)

Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt]: Yes, a fix is in the queue.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt [hunk 4]
```diff
@@ -40,15 +44,29 @@ class ForbiddenComment(config: Config = Config.empty) : Rule(config) {
...
+    private fun checkForbiddenComment(text: String, comment: PsiElement) {
         if (allowedPatterns.pattern.isNotEmpty() && allowedPatterns.containsMatchIn(text)) return
 
         values.forEach {
             if (text.contains(it, ignoreCase = true)) {
-                report(CodeSmell(issue, Entity.from(comment), "This comment contains text that has been " +
-                        "defined as forbidden in detekt."))
+                report(
+                    CodeSmell(
+                        issue, Entity.from(comment), "This comment contains text that has been " +
```
Comment (arturbosch) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:66]:
```suggestion
                        issue, Entity.from(comment), "This comment contains '$it' that has been " +
```

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 2 above)
Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:66]: This is actually the default IntelliJ format.
I used the IntelliJ extract function option.
If you like, I can revert back to the old format.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 4 above)
Comment (arturbosch) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:66]: We can actually be specific here. This would help when just reading the reports.

**Review by arturbosch — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 4 above)
Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:66]: This would then report the whole comment. I'm not sure whether we want to print the whole text. Detekt already outputs the flagged entity.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 2 above)
Comment (arturbosch) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:66]: Only a nit here. Feel free to leave it that way.
IntelliJ should allow both formats I think. I would prefer a strict mode with an idempotent result :).

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 1 above)
Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt:53]: Nope, I couldn't find a separate `visit` method.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt (hunk 4 above)
Comment (arturbosch) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt]: `it` would be in that block `TODO:` for example.
Do you mean it outputs it in the html report?
The console report would just print `"ForbiddenComment - This comment contains text that has been defined as forbidden in detekt."  right?

Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ForbiddenComment.kt]: Yes, thanks for the explanation. I'll change it. That makes sense.

File: config/detekt/detekt.yml [hunk 5]
```diff
@@ -84,6 +84,7 @@ style:
   ForbiddenComment:
     active: true
     values: ['TODO:', 'FIXME:', 'STOPSHIP:', '@author']
+    excludes: ['**/detekt-rules-style/**/ForbiddenComment.kt']
```
Comment (BraisGabin) [inline config/detekt/detekt.yml:87]: 😂 This is funny we need to exclude the rule from itself.

**Review by BraisGabin — APPROVED** [review]

File: config/detekt/detekt.yml (hunk 5 above)
Comment (schalkms) [reply config/detekt/detekt.yml:87]: The `Suppress` annotation won't work for comments in this case. That's the consequence here.
