### PR TITLE
Fix modifier order value class

### LINKED ISSUE #3717: False positive on ModifierOrder for value classes in Kotlin 1.5
```
@JvmInline
private value class Foo(val bar: Int)
```

## Expected Behavior
Should not fail the ModifierOrder check

## Observed Behavior
It does

## Your Environment
* Version of detekt used: 1.16.0
* Version of Gradle used (if applicable): 7.0

### PR DESCRIPTION
**Pull request by eygraber**
On top of https://github.com/detekt/detekt/pull/3718

Fixes #3717

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrder.kt [hunk 1]
```diff
@@ -75,6 +76,7 @@ class ModifierOrder(config: Config = Config.empty) : Rule(config) {
         ENUM_KEYWORD, ANNOTATION_KEYWORD, FUN_KEYWORD,
         COMPANION_KEYWORD,
         INLINE_KEYWORD,
+        VALUE_KEYWORD,
```
Comment (chao2zhang) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrder.kt:79]: It seems reasonable to put `value` here because `value class` is `inline class`. However, would you mind creating a PR for Kotlin coding convention [here](https://kotlinlang.org/docs/coding-conventions.html#modifiers-order) since it does not include the `value` modifier yet?

**Review by chao2zhang — APPROVED** [review]

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrder.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrder.kt:79]: I just created that PR: https://github.com/JetBrains/kotlin-web-site/pull/2300

Should we wait for it to be merged before merging this? Or can we merge it and revert it in case it is rejected?

Comment (chao2zhang) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrder.kt:79]: I am inclined to merge it now since this will impact the correctness when running Detekt on Kotlin 1.5 code. See https://github.com/detekt/detekt/pull/3810/files#r637354618

**Comment by netroy** [comment]
@cortinico @chao2zhang can we **please** have a new release that'd include this fix?
