### PR TITLE
[MaxLineLength] Fix signature in for blank characters in the Baseline

### LINKED ISSUE #4480: Baseline not catching multiline string literals correctly
## Expected Behavior
A MaxLineLength with multiline string literals will be written in the baseline and not causing problems when running `detekt`.

## Observed Behavior
It's written in the baseline file as follows:

```
<ID>MaxLineLength:MainActivity.kt$MainActivity$ </ID>
```
The task fails. I think the signature is incorrect.

## Steps to Reproduce
- Checkout my project: https://github.com/jelleheemskerk/detekt-bug
- Run `./gradlew detekt`

## Context
I'm trying to integrate detekt with our existing codebase. We use multiline string literals with JSON data for our tests. I don't seem to have this issue on **1.18.1**.

## Your Environment
* Version of detekt used: **1.19.0**
* Version of Gradle used (if applicable): **7.0.2**
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/ix7enmucwqthe
* Operating System and version: **Mac OS 12.1**
* Link to your project (if it's a public repository): https://github.com/jelleheemskerk/detekt-bug

### PR DESCRIPTION
**Pull request by marschwar**
This fixes #4480

### CODE REVIEW

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt [hunk 1]
```diff
@@ -8,6 +8,7 @@ import io.gitlab.arturbosch.detekt.test.TestConfig
 import io.gitlab.arturbosch.detekt.test.assertThat
 import org.spekframework.spek2.Spek
 import org.spekframework.spek2.style.specification.describe
+import org.assertj.core.api.Assertions.assertThat as doAssert
```
Comment (marschwar) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt:11]: @BraisGabin This is a probably unintended side effect of #4437
Do have a better idea on how to fix it?

Comment (BraisGabin) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt:11]: I don't understand, what's unintended here? I assume that you are using `doAssert` because you don't want to use `io.gitlab.arturbosch.detekt.test.assertThat`. But I think that you could remove this last one and everything should work the same.

**Review by BraisGabin — APPROVED** [review]

**Comment by marschwar** [comment]
The question what is the best way to use 
`io.gitlab.arturbosch.detekt.test.assertThat{Finding)` and 
`org.assertj.core.api.Assertions.assertThat(List<String>)` in the same file?

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt (hunk 1 above)
Comment (marschwar) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt:11]: The question what is the best way to use
io.gitlab.arturbosch.detekt.test.assertThat{Finding) and
org.assertj.core.api.Assertions.assertThat(List<String>) in the same file?

Comment (BraisGabin) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt:11]: Isn't `io.gitlab.arturbosch.detekt.test.assertThat` an extension of `org.assertj.core.api.Assertions.assertThat`? I thought that we could always use `io.gitlab.arturbosch.detekt.test.assertThat` instead of `org.assertj.core.api.Assertions.assertThat`.

Comment (marschwar) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLengthSpec.kt:11]: No, the detekt versions support `Finding`, `List<Finding>` and `ThresholdedCodeSmell`. For all other assertions `org.assertj.core.api.Assertions.assertThatXXX` are used. This is only a problem if the test uses both. I see 3 options to mitigate this

* allow the assertJ import again
* rename the detekt functions (or provide aliases) to  something like `assertThatFinding`
* use the alias import the way it was done here in this pr

**Comment by BraisGabin** [comment]
If we end up reverting #4335 would we want to merge this anyway? Because if we don't want this if we revert #4335 probably what we should do is just revert #4335.

**Review by cortinico — APPROVED** [review]

**Comment by marschwar** [comment]
I vote to merge this regardless as it allows to differentiate between two similar violations in the same file
