### PR TITLE
`ExpressionBodySyntax`: don't report if multiple returns in when expressions (Closes #7829)

### LINKED ISSUE #7829: `ExpressionBodySyntax` false positive when more than one return statement
## Expected Behavior
When function has more than one return statement, `ExpressionBodySyntax` should not be triggered.

## Observed Behavior
It is.

## Steps to Reproduce
Example code:

```kotlin
class PromoCodeSummaryMapper {
    fun PromoApplied.toPresentable(currency: Currency): PromoCodeSummary? {
        return PromoCodeSummary(
            code = code,
            type = when {
                promoFreeDelivery == true -> PromoCodeSummary.FreeDelivery
                promoDiscountAmount != null -> PromoCodeSummary.Discount(Amount(-promoDiscountAmount, currency))
                else -> return null
            },
        )
    }
}
```

> .../PromoCodeSummaryMapper.kt:11:9: Functions with exact one statement, the return statement, can be rewritten with ExpressionBodySyntax. [ExpressionBodySyntax]

When I do as suggested by the issue, I get IDE error:

Screenshot 2024-12-10 at 10 22 02

## Your Environment

* Version of detekt used: 1.23.7
* Version of Gradle used (if applicable): 8.10
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by paolorotolo**
This PR fixes #7829, not reporting a `ExpressionBodySyntax` if there are multiple return expressions in `when` statements.

This code is now compliant:
```kotlin
    fun stuff(): Pair<String, String>? {
        return Pair(
            first = "",
            second = when {
                true -> ""
                else -> return null 
            }
        )
    }
```

### CODE REVIEW

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt [hunk 1]
```diff
@@ -69,6 +72,11 @@ class ExpressionBodySyntax(config: Config) : Rule(
     private fun KtExpression.singleReturnStatement(): KtReturnExpression? =
         (this as? KtBlockExpression)?.statements?.singleOrNull() as? KtReturnExpression
 
+    private fun KtReturnExpression.containsReturnInWhenExpressions(): Boolean =
+        anyDescendantOfType<KtReturnExpression> {
+            (it.parent as? KtWhenEntry) != null
```
Comment (schalkms) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt:77]:
```suggestion
            it.parent is KtWhenEntry
```

**Review by schalkms — COMMENTED** [review]
Thank you for fixing this issue - looks good!
The explicit type cast could be removed to optimise the check.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt:77]: Should we have a rule to find this pattern? It should be an easy rule.

Comment (schalkms) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt:77]: Good idea! Definitely, such a rule would be of great value.

> Should we have a rule to find this pattern? It should be an easy rule.

Comment (paolorotolo) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt]: Good catch, thank you!

**Review by schalkms — APPROVED** [review]
