### PR TITLE
CanBeNonNullable: Fix false positive when property is defined after assignment

### LINKED ISSUE #6199: False Positive in CanBeNonNullable
## Expected Behavior
```
class FalsePositive {                        

    fun release() {
        fooBarObj = null
    }

    private var fooBarObj: FooBar? = FooBar()

}

class FooBar {
    // declare member variables and do something
}
```
This tool should not give any issue with CanBeNonNullable.

## Observed Behavior

CanBeNonNullable issue is coming

## Steps to Reproduce

```
@Test
fun failingTc() {
    val code = """
        class FalsePositive {                        

            fun release() {
                fooBarObj = null
            }

            private var fooBarObj: FooBar? = FooBar()

        }

        class FooBar {
            // declare member variables and do something
        }
    """.trimIndent()
    assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
}
```

## Your Environment

* Version of detekt used: 1.23.0 (latest) 
* Version of Gradle used (if applicable): 7.x

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #6199

### CODE REVIEW

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt [hunk 1]
```diff
@@ -143,6 +143,11 @@ class CanBeNonNullableSpec(val env: KotlinCoreEnvironment) {
                     private fun buzz(bizz: Int): Int? {
                         return if (bizz % 2 == 0) null else bizz
                     }
+
+                    fun baz() {
```
Comment (atulgpt) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt:147]: We can also add TC like below(to prevent any future break around false -ve)
```
fun baz() {
    val r = object: Runnable {
        var g: Int? = null
        override fun run() { g = null }
    }
}

private var g: Int? = 0
```

```
fun baz() {
    val g: Int? = null
    g = null
}
private var g: Int? = 0
```
Potential false +ve TC
```
fun baz(a: Int?) {
    g = a // now this should not be reported
}
private var g: Int? = 0
```
```
fun baz(a: Int?) {
    g = a?.also { println("assigning baz a to g") }
}
private var g: Int? = 0
```

Comment (t-kameyama) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt:178]: 241fb90188c908b9a5ea3bfe7477db0cd24c0370

**Review by 3flex — APPROVED** [review]
