### PR TITLE
Better error classification in Gradle Enterprise.

### LINKED ISSUE #4585: Prefix exception message with `Lint failed` or `Analysis failed`
In order to correctly classify errors in Gradle Enterise, exception messages should be prefixed with any of the messages listed below:

- Analysis failed
- Check failed
- Compilation failed
- Code generation failed
- Generation failed
- Lint failed
- Processing failed
- Test failed
- Tests failed
- Testing failed
- Verification failed

See docs for more information:
https://docs.gradle.com/enterprise/failure-classification/#verification_failures

## Observed Behavior
The current exception message `Build failed with 2 weighted issues.`

Happy to contribute this change.

### PR DESCRIPTION
**Pull request by runningcode**
Use `Lint failed` instead of `Build failed` in exception

Fixes #4585

[Correctly classified error](https://ge.solutions-team.gradle.com/scans/failures?failures.failureClassification=verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:detektAll%27.%0A%3E%20*%20failed%20with%20*%20weighted%20issues.&search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin)

[Incorrectly classified error](https://ge.solutions-team.gradle.com/scans/failures?failures.failureClassification=non_verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:detektAll%27.%0A%3E%20*%20failed%20with%20*%20weighted%20issues.&search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin)

### CODE REVIEW

**Comment by cortinico** [comment]
I'd change to "Analysis failed" as "Lint" is an overloaded term in the Android space

**Comment by runningcode** [comment]
@cortinico I've changed it. It seems that some of the tests that are failing are not picking up the new detekt artifact. Do you know why?

**Comment by cortinico** [comment]
> It seems that some of the tests that are failing are not picking up the new detekt artifact. Do you know why?

@3flex can tell you more here. The issue is that our build setup is configured to don't use composite builds (I never recall why). So essentially you're testing against the latest released version of the Gradle plugin (as the failing tests are only those on `:detekt-gradle-plugin:functionalTest`).

Unless we switch to use the included build here:
https://github.com/detekt/detekt/blob/f15ce50d5e87ea43b1b940e2f2e0ed70fe3072fb/settings.gradle.kts#L14

We should probably keep the test update as a draft PR and merge it once we're about to release.

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/invoke/DetektInvoker.kt [hunk 1]
```diff
@@ -66,7 +66,7 @@ internal class DefaultCliInvoker(
         }
     }
 
-    private fun isBuildFailure(msg: String) = "Analysis failed with" in msg && "issues" in msg
+    private fun isBuildFailure(msg: String) = "Build failed with" in msg && "issues" in msg
```
Comment (runningcode) [inline detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/invoke/DetektInvoker.kt:69]: @cortinico I had to revert this change to the Gradle plugin since the failure detection would break. Is the Gradle plugin published together with the detekt-core artifact?

**Comment by runningcode** [comment]
Here is the follow up PR: https://github.com/detekt/detekt/pull/4588

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/invoke/DetektInvoker.kt (hunk 1 above)
Comment (cortinico) [reply detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/invoke/DetektInvoker.kt:69]: Yes they are 👍

**Review by cortinico — APPROVED** [review]

**Review by chao2zhang — APPROVED** [review]
