### PR TITLE
Less noisy output for detekt with Type solving

### LINKED ISSUE #3684: Noisy output of detekt on type solving mode
## Expected Behavior
`detektMain` and `detektTest` quietly. At least in `detekt` that we suppose to have it configured correctly.

## Observed Behavior
They don't: https://scans.gradle.com/s/q7fdffszk5aim/console-log/raw

## Steps to Reproduce
Run `./gradlew detektMain detektTest --rerun-tasks` in the main branch of this project

## Issues detected
I think that we have 3 different issues but they could be related.

~~1. Empty lines~~ (fixed by #3909)
```
:detekt-core:detektMain

:detekt-formatting:detektMain
:detekt-generator:detektMain









:detekt-gradle-plugin:detektMain





:detekt-metrics:detektMain
```
2. Errors complaining about `internal` modifiers:
```
:detekt-metrics:detektTest
//Users/brais/projects/detekt/detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/AnalyzerSpec.kt:28:28: error: cannot access 'Analyzer': it is internal in 'io.gitlab.arturbosch.detekt.core'
            val analyzer = Analyzer(settings, listOf(StyleRuleSetProvider()), emptyList())
                           ^
```
3. Errors that show that the type solving is not working as expected:
```
//Users/brais/projects/detekt/detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormatSpec.kt:47:67: error: no value passed for parameter 'body'
                assertThat(manuallySuppressedIssues).anySatisfy { it.startsWith("LongParameterList") }
```

```
//Users/brais/projects/detekt/detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormatSpec.kt:47:70: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun File.startsWith(other: File): Boolean defined in kotlin.io
public fun File.startsWith(other: String): Boolean defined in kotlin.io
public fun CharSequence.startsWith(char: Char, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun CharSequence.startsWith(prefix: CharSequence, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun CharSequence.startsWith(prefix: CharSequence, startIndex: Int, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun String.startsWith(prefix: String, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun String.startsWith(prefix: String, startIndex: Int, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
                assertThat(manuallySuppressedIssues).anySatisfy { it.startsWith("LongParameterList") }
```

```
//Users/brais/projects/detekt/detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormatSpec.kt:48:17: error: overload resolution ambiguity: 
public open fun <ELEMENT : Any!> assertThat(p0: (MutableList<out TypeVariable(ELEMENT)!>..List<TypeVariable(ELEMENT)!>?)): ListAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: File!): AbstractFileAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: InputStream!): AbstractInputStreamAssert<*, out InputStream!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Class<*>!): ClassAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: StringBuffer!): AbstractCharSequenceAssert<*, out CharSequence!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: StringBuilder!): AbstractCharSequenceAssert<*, out CharSequence!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: BigDecimal!): AbstractBigDecimalAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: BigInteger!): AbstractBigIntegerAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: URI!): AbstractUriAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: URL!): AbstractUrlAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Path!): AbstractPathAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Duration!): AbstractDurationAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Instant!): AbstractInstantAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LocalDate!): AbstractLocalDateAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LocalDateTime!): AbstractLocalDateTimeAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LocalTime!): AbstractLocalTimeAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: OffsetDateTime!): AbstractOffsetDateTimeAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: OffsetTime!): AbstractOffsetTimeAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Period!): AbstractPeriodAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: ZonedDateTime!): AbstractZonedDateTimeAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Date!): AbstractDateAssert<*>! defined in org.assertj.core.api.Assertions
public open fun <VALUE : Any!> assertThat(p0: Optional<TypeVariable(VALUE)!>!): OptionalAssert<TypeVariable(VALUE)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: OptionalDouble!): OptionalDoubleAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: OptionalInt!): OptionalIntAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: OptionalLong!): OptionalLongAssert! defined in org.assertj.core.api.Assertions
public open fun <ELEMENT : Any!> assertThat(p0: Spliterator<TypeVariable(ELEMENT)!>!): SpliteratorAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun <RESULT : Any!> assertThat(p0: CompletableFuture<TypeVariable(RESULT)!>!): CompletableFutureAssert<TypeVariable(RESULT)!>! defined in org.assertj.core.api.Assertions
public open fun <RESULT : Any!> assertThat(p0: CompletionStage<TypeVariable(RESULT)!>!): CompletableFutureAssert<TypeVariable(RESULT)!>! defined in org.assertj.core.api.Assertions
public open fun <RESULT : Any!> assertThat(p0: Future<TypeVariable(RESULT)!>!): FutureAssert<TypeVariable(RESULT)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: AtomicBoolean!): AtomicBooleanAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: AtomicInteger!): AtomicIntegerAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: AtomicIntegerArray!): AtomicIntegerArrayAssert! defined in org.assertj.core.api.Assertions
public open fun <OBJECT : Any!> assertThat(p0: AtomicIntegerFieldUpdater<TypeVariable(OBJECT)!>!): AtomicIntegerFieldUpdaterAssert<TypeVariable(OBJECT)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: AtomicLong!): AtomicLongAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: AtomicLongArray!): AtomicLongArrayAssert! defined in org.assertj.core.api.Assertions
public open fun <OBJECT : Any!> assertThat(p0: AtomicLongFieldUpdater<TypeVariable(OBJECT)!>!): AtomicLongFieldUpdaterAssert<TypeVariable(OBJECT)!>! defined in org.assertj.core.api.Assertions
public open fun <VALUE : Any!> assertThat(p0: AtomicMarkableReference<TypeVariable(VALUE)!>!): AtomicMarkableReferenceAssert<TypeVariable(VALUE)!>! defined in org.assertj.core.api.Assertions
public open fun <VALUE : Any!> assertThat(p0: AtomicReference<TypeVariable(VALUE)!>!): AtomicReferenceAssert<TypeVariable(VALUE)!>! defined in org.assertj.core.api.Assertions
public open fun <ELEMENT : Any!> assertThat(p0: AtomicReferenceArray<TypeVariable(ELEMENT)!>!): AtomicReferenceArrayAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun <FIELD : Any!, OBJECT : Any!> assertThat(p0: AtomicReferenceFieldUpdater<TypeVariable(OBJECT)!, TypeVariable(FIELD)!>!): AtomicReferenceFieldUpdaterAssert<TypeVariable(FIELD)!, TypeVariable(OBJECT)!>! defined in org.assertj.core.api.Assertions
public open fun <VALUE : Any!> assertThat(p0: AtomicStampedReference<TypeVariable(VALUE)!>!): AtomicStampedReferenceAssert<TypeVariable(VALUE)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LongAdder!): LongAdderAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: DoublePredicate!): DoublePredicateAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: IntPredicate!): IntPredicateAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LongPredicate!): LongPredicateAssert! defined in org.assertj.core.api.Assertions
public open fun <T : Any!> assertThat(p0: Predicate<TypeVariable(T)!>!): PredicateAssert<TypeVariable(T)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: DoubleStream!): ListAssert<Double!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: IntStream!): ListAssert<Int!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LongStream!): ListAssert<Long!>! defined in org.assertj.core.api.Assertions
public open fun <ELEMENT : Any!> assertThat(p0: Stream<out TypeVariable(ELEMENT)!>!): ListAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun <T : Any!> assertThat(p0: Array<(out) TypeVariable(T)!>!): ObjectArrayAssert<TypeVariable(T)!>! defined in org.assertj.core.api.Assertions
public open fun <T : Any!> assertThat(p0: Array<(out) Array<(out) TypeVariable(T)!>!>!): Object2DArrayAssert<TypeVariable(T)!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) BooleanArray!>!): Boolean2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) ByteArray!>!): Byte2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) CharArray!>!): Char2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) DoubleArray!>!): Double2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) FloatArray!>!): Float2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) IntArray!>!): Int2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) LongArray!>!): Long2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Array<(out) ShortArray!>!): Short2DArrayAssert! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Boolean): AbstractBooleanAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Boolean!): AbstractBooleanAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: BooleanArray!): AbstractBooleanArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Byte): AbstractByteAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Byte!): AbstractByteAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: ByteArray!): AbstractByteArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Char): AbstractCharacterAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Char!): AbstractCharacterAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: CharArray!): AbstractCharArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: CharSequence!): AbstractCharSequenceAssert<*, out CharSequence!>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Double): AbstractDoubleAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Double!): AbstractDoubleAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: DoubleArray!): AbstractDoubleArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Float): AbstractFloatAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Float!): AbstractFloatAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: FloatArray!): AbstractFloatArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Int): AbstractIntegerAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Int!): AbstractIntegerAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: IntArray!): AbstractIntArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Long): AbstractLongAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Long!): AbstractLongAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: LongArray!): AbstractLongArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Short): AbstractShortAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Short!): AbstractShortAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: ShortArray!): AbstractShortArrayAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: String!): AbstractStringAssert<*>! defined in org.assertj.core.api.Assertions
public open fun assertThat(p0: Throwable!): AbstractThrowableAssert<*, out Throwable!>! defined in org.assertj.core.api.Assertions
public open fun <ELEMENT : Any!> assertThat(p0: (Mutable)Iterable<TypeVariable(ELEMENT)!>!): IterableAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun <ELEMENT : Any!> assertThat(p0: (Mutable)Iterator<TypeVariable(ELEMENT)!>!): IteratorAssert<TypeVariable(ELEMENT)!>! defined in org.assertj.core.api.Assertions
public open fun <K : Any!, V : Any!> assertThat(p0: (Mutable)Map<TypeVariable(K)!, TypeVariable(V)!>!): MapAssert<TypeVariable(K)!, TypeVariable(V)!>! defined in org.assertj.core.api.Assertions
public open fun <T : Any!> assertThat(p0: AssertProvider<TypeVariable(T)!>!): TypeVariable(T)! defined in org.assertj.core.api.Assertions
                assertThat(manuallySuppressedIssues).anySatisfy { it.startsWith("LongMethod") }
                ^
```

## Context
If we want to move type solving out of experimental we need to face this problems and solve them. A possible solution could be to stop evolving the current solution and move to the compiler plugin. I think that all us agree that we want to go in that direction so probably now is the time to go it. I'm assuming that this kind of issues doesn't appear in the compiler plugin but I didn't use it yet.

@3flex I would like to know your thought on this.

## Your Environment
* Version of detekt used: main
* Version of Gradle used (if applicable): 5.8.3
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/q7fdffszk5aim/
* Operating System and version: Mac
* Link to your project (if it's a public repository): https://github.com/detekt/detekt/

### PR DESCRIPTION
**Pull request by BraisGabin**
This PR changes this output:

```
> Task :detekt-parser:detektTest
//Users/brais.gabin/Workspace/detekt/detekt-parser/src/test/kotlin/io/github/detekt/parser/KotlinEnvironmentUtilsSpec.kt:23:50: error: cannot access 'getKotlinLanguageVersion': it is internal in 'io.github.detekt.parser'
            val languageVersion = classpathFiles.getKotlinLanguageVersion()
                                                 ^
//Users/brais.gabin/Workspace/detekt/detekt-parser/src/test/kotlin/io/github/detekt/parser/KtCompilerSpec.kt:82:33: error: cannot access 'determineLineSeparator': it is internal in 'io.github.detekt.parser'
            assertThat("1\r\n2".determineLineSeparator()).isEqualTo("\r\n")
                                ^
//Users/brais.gabin/Workspace/detekt/detekt-parser/src/test/kotlin/io/github/detekt/parser/KtCompilerSpec.kt:86:31: error: cannot access 'determineLineSeparator': it is internal in 'io.github.detekt.parser'
            assertThat("1\n2".determineLineSeparator()).isEqualTo("\n")
                              ^
//Users/brais.gabin/Workspace/detekt/detekt-parser/src/test/kotlin/io/github/detekt/parser/KtCompilerSpec.kt:90:31: error: cannot access 'determineLineSeparator': it is internal in 'io.github.detekt.parser'
            assertThat("1\r2".determineLineSeparator()).isEqualTo("\r")
                              ^
```

To this one:
```
> Task :detekt-parser:detektTest
The BindingContext was created with 4 issues. Run detekt with --debug to see the error messages.
```

It isn't a real fix. We shouldn't have those compilation errors, but at least now they are hidden behind `--debug`

Any idea to improve this message is more than welcome:

> The BindingContext was created with 4 issues. Run detekt with --debug to see the error messages.

closes #3684

### CODE REVIEW

File: detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt [hunk 1]
```diff
@@ -1,44 +0,0 @@
-package io.gitlab.arturbosch.detekt.core
-
-import org.assertj.core.api.Assertions.assertThat
-import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
-import org.spekframework.spek2.Spek
-import org.spekframework.spek2.style.specification.describe
-import java.io.PrintStream
-
-internal object DetektMessageCollectorSpec : Spek({
```
Comment (schalkms) [inline detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt:9]: I think tests for the new functionality would be beneficial here. This way it's also documented by having unit tests for the newly introduced message collector instead of deleting the outdated tests.

**Review by schalkms — COMMENTED** [review]
Nice fix! This problem really annoyed users when debugging detekt or any other console output. Please see my comment regarding tests. Otherwise, this PR looks great.

File: detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt:9]: I don't see what testing `DetektMessageCollector` provides. For that reason I removed this tests.

I'm going to try if I can test `generateBindingContext`. But I'm afraid it will need to create a real compiler instance and make it build the BindingContext to test it properly.

Comment (chao2zhang) [reply detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt:9]: The tests were added in https://github.com/detekt/detekt/pull/3909/files and I assumed they were intended for improving the test coverage.

Comment (BraisGabin) [reply detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/DetektMessageCollectorSpec.kt:9]: Done.

**Review by chao2zhang — APPROVED** [review]
