### PR TITLE
[KMP] Fix resolution of Android test classpaths

### LINKED ISSUE #3840: Tasks `detektAndroidDebugUnitTest` `detektAndroidReleaseUnitTest` and `detektAndroidDebugAndroidTest` fail to run in a KMM project
## Expected Behavior

Able to run these tasks and gradle will run

## Observed Behavior

An exception is thrown and no tasks are run

```
Could not determine the dependencies of task ':pangea-core:detektAndroidReleaseUnitTest'.
> Could not resolve all task dependencies for configuration ':pangea-core:releaseUnitTestCompileClasspath'.
   > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :pangea-core:
       - Configuration ':pangea-core:releaseApiElements' variant android-aidl declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-aidl' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
```

## Context

Since these tasks are part of the check task, that task cannot be run.
This can be worked around by disabling the tasks.

The project has Kotlin targets for iOS, JVM, and Android.

```
kotlin {
    ios()
    jvm()
    android()
   
    more configuration
}
```

## Your Environment

* Version of detekt used: 1.16.0 and 1.71.2
* Version of Gradle used (if applicable): 6.7.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: MacOS 11.3.1
* Link to your project (if it's a public repository):
* AGP 4.2.1

### PR DESCRIPTION
**Pull request by cortinico**
This PR depends on #4025

The approach used inside the KMP support for `detekt-gradle-plugin` was not working correctly for tests sourcesets of Android targets. I fixed it by delegating the creation of detekt tasks for `android()` targets to `DetektAndroid`. This will also make sure that the behavior between a pure Android project and a KMP project with an Android target is closer.

Fixes #3840

### CODE REVIEW

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt [hunk 1]
```diff
@@ -38,54 +40,83 @@ internal class DetektMultiplatform(private val project: Project) {
...
                         .fold(evaluatedProject.files() as FileCollection) { collection, next -> collection.plus(next) }
 
-                    val detektTaskProvider = evaluatedProject.registerDetektTask(
-                        DetektPlugin.DETEKT_TASK_NAME + taskSuffix,
-                        extension
-                    ) {
-                        setSource(inputSource)
-                        if (runWithTypeResolution) {
-                            classpath.setFrom(inputSource, compilation.compileDependencyFiles)
+                    if (compilation is KotlinJvmAndroidCompilation) {
```
Comment (chao2zhang) [inline detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt:43]: Do you think it is worth extracting this into a separate function? This method has code that is already highly nested and we are incrementing the depth.

**Review by chao2zhang — COMMENTED** [review]
Did we test with AGP 4.2 so far? (Not a blocking question but something I am interested in)

**Comment by cortinico** [comment]
> Did we test with AGP 4.2 so far? (Not a blocking question but something I am interested in)

We're already on AGP `4.2.0` 👍

**Review by BraisGabin — APPROVED** [review]

File: detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt (hunk 1 above)
Comment (cortinico) [reply detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektMultiplatform.kt:40]: Yup I've refactored it a bit.

**Review by chao2zhang — APPROVED** [review]

**Comment by chao2zhang** [comment]
There is a `UnnecessaryLet` finding in the PR.
