### PR TITLE
Handle MultiRules in Suppressors

### LINKED ISSUE #4230: ignoreAnnotated config doesn't work on FunctionNaming rule
## Expected Behavior
Being able to suppress `FunctionNaming` rule on functions annotated with `@Composable`

## Observed Behavior
All `@Composable` function names reported as violations

## Steps to Reproduce
Run detekt 1.19.0-RC1 analysis on a project with Composable functions

## Context
It seems that naming rules are all run through one MulitRule: [NamingRules](https://github.com/detekt/detekt/blob/28830b8db5adb37c08c65e70f9251d9396681b24/detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingRules.kt) which is not ConfigAware so [getSuppressors](https://github.com/detekt/detekt/blob/edabb6f2b98cf4021606ff48e6acd13be1ef6207/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt#L13) returns empty list

## Your Environment
* Version of detekt used: 1.19.0-RC-1

### PR DESCRIPTION
**Pull request by BraisGabin**
`MultiRule`s are a pain to maintain (more about this here: #4240). But for now this code should do the trick.

~I don't know how to test this properly. I manually tested it.~

Fixes #4230

### CODE REVIEW

**Comment by cortinico** [comment]
> I don't know how to test this properly. I manually tested it.

I believe you should be able to unit test this, no?

**Comment by BraisGabin** [comment]
They are not the best test I ever wrote but they should be enough.

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt [hunk 1]
```diff
@@ -3,18 +3,39 @@ package io.gitlab.arturbosch.detekt.core.suppressors
...
+        is ConfigAware -> buildSuppressors(rule)
+        else -> emptyList()
+    }
+}
+
+private class InnerSuppressor(
+    private val rule: Rule,
+    private val suppressor: Suppressor
+) : Suppressor {
+    override fun invoke(finding: Finding): Boolean {
```
Comment (chao2zhang) [inline detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt:34]: One benefit using `fun interface` over `typealias` is that the method name would make more sense without looking at the documentation. `shouldSuppress(finding: Finding): Boolean` is definitely more contextual than `invoke(finding: Finding)`

Additionally, we could take `List<Suppressor>` as a `CompositeSuppressor` to simplify the test code.

I don't think it is necessary to address this in this PR. But would like to know your thoughts.

File: detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+                """
+                fun foo() = Unit
+                """.trimIndent()
+            )
+            CodeSmell(ARule().issue, Entity.from(root), "")
+        }
+        val ignorableCodeSmell by memoized {
+            val root = compileContentForTest(
+                """
+                @file:Composable
```
Comment (chao2zhang) [inline detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt:31]: Practically, the @Composable should an annotation on the function, not at the file leve.

**Review by chao2zhang — APPROVED** [review]

File: detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt (hunk 2 above)
Comment (BraisGabin) [reply detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt:31]: Yes, it could. But then I can't report directly `root`. I should find the `KtFunction` inside `root`. For that reason I added the annotation as `@file:`

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt:34]: About `fun interface`, I'm ok. The only "problem" is that for instantiate it instead of doing: `{}` we should need to write `Suppressor {}`. But I agree that invoke isn't a good name. I'm going to change it.

About `CompositeSuppressor` I don't think it will make the code simpler.

Comment (BraisGabin) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt:34]: I just did the `fun interface`... And I'm not sure if I like it more or less: https://github.com/detekt/detekt/commit/43573a919e71380ab7fc31a53f3b4f1e284971a4

What do you thinkg? I like the old `suppress(finding)` syntax. But, when implementing a non-anonymous `Suppressor` I agree that the `shouldSupress` is better.

Comment (chao2zhang) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt:34]: The commit [43573a9](https://github.com/detekt/detekt/commit/43573a919e71380ab7fc31a53f3b4f1e284971a4) looks better in my opinion.

File: detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt (hunk 2 above)
Comment (chao2zhang) [reply detekt-core/src/test/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/SuppressorsSpec.kt:31]: Makes sense. I think we still have sufficient coverage with the existing implementation.

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/suppressors/Suppressors.kt]: Added

**Review by chao2zhang — APPROVED** [review]
