### PR TITLE
Fix redundant empty tags in baseline XML

### LINKED ISSUE #7622: Empty XML tags in baseline files
## Expected Behavior
An empty XML tag should be self-closing, e.g. `<ManuallySuppressedIssues />`.

## Observed Behavior
In the generated baseline XML files, an XML tag with no body is simply left empty, e.g. `<ManuallySuppressedIssues></ManuallySuppressedIssues>`.

## Steps to Reproduce

If you create any Kotlin module with a Detekt issue (e.g. a magic number) and run `./gradlew detektBaseline` on it, it'll generate the baseline file. You can see the empty-body `ManuallySuppressedIssues` tag for yourself. If there are no Detekt issues, the same will be true for the `CurrentIssues` tag.

Live examples in my repo: [One](https://github.com/JordanLongstaff/ArtemisAgent/blob/main/IAN/udp/detekt-baseline.xml) and [Two](https://github.com/JordanLongstaff/ArtemisAgent/blob/main/IAN/util/detekt-baseline.xml)

## Context

I am programming in Android Studio, which complains about the empty tags. These complaints show up as warnings in the Code Analysis view. If I replace the tags with self-closing tags, the warnings disappear; however, Detekt will still re-generate empty tags to replace them if the `detektBaseline` task is run again.

## Your Environment

* Version of detekt used: 1.23.7
* Version of Gradle used (if applicable): 8.6.0
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): [here](https://github.com/JordanLongstaff/ArtemisAgent)

### PR DESCRIPTION
**Pull request by JordanLongstaff**
Fixes #7622

The `CurrentIssues` tag is reduced to a self-closing tag if there are no current issues. Likewise for the `ManuallySuppressedIssues` tag.

### CODE REVIEW

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormat.kt [hunk 1]
```diff
@@ -54,11 +54,18 @@ internal class BaselineFormat : BaselineProvider {
     private fun XMLStreamWriter.save(baseline: Baseline) {
         document {
             tag(SMELL_BASELINE) {
-                tag(MANUALLY_SUPPRESSED_ISSUES) {
-                    baseline.manuallySuppressedIssues.forEach { tag(ID, it) }
+                if (baseline.manuallySuppressedIssues.isNotEmpty()) {
+                    tag(MANUALLY_SUPPRESSED_ISSUES) {
+                        baseline.manuallySuppressedIssues.forEach { tag(ID, it) }
+                    }
                 }
```
Comment (cortinico) [inline detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormat.kt:61]: You should `writeEmptyElement(MANUALLY_SUPPRESSED_ISSUES)` here as well

**Review by cortinico — CHANGES_REQUESTED** [review]

**Review by cortinico — APPROVED** [review]

**Comment by BraisGabin** [comment]
Thanks for the pr
