### PR TITLE
UnnecessaryAbstractClass: fix false positive when the abstract class has properties in the primary constructor

### LINKED ISSUE #4626: UnnecessaryAbstractClass does not consider unimplemented base properties
## Expected Behavior
`UnnecessaryAbstractClass` should not warn for classes that don't implement the full interface of their base types. 

## Observed Behavior
The following code should not give an `UnnecessaryAbstractClass` warning for `Test`.

```
abstract class Test( val par: Int ) : BaseAbstract

interface BaseAbstract
{
    fun test(): Int
}
```

It gives this warning for the `Test` class.

> An abstract class without an abstract member can be refactored to a concrete class. [UnnecessaryAbstractClass]

## Your Environment

* Version of detekt used: 1.20.0-RC1

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #4626

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]

**Review by cortinico — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt [hunk 1]
```diff
@@ -77,53 +75,47 @@ class UnnecessaryAbstractClass(config: Config = Config.empty) : Rule(config) {
...
+                if (abstractMembers.isEmpty() && !hasInheritedMember(true)) {
+                    report(CodeSmell(issue, Entity.from(this), noAbstractMember))
+                    return
+                }
+                if (abstractMembers.any { it.isInternal() || it.isProtected() } || hasConstructorParameter()) {
+                    return
+                }
+                if (concreteMembers.isEmpty() && !hasInheritedMember(false)) {
+                    report(CodeSmell(issue, Entity.from(this), noConcreteMember))
+                }
```
Comment (chao2zhang) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt:97]: Nit: The previous `detectAbstractAndConcreteType()` seems cleaner to me.

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt [hunk 2]
```diff
@@ -77,53 +75,47 @@ class UnnecessaryAbstractClass(config: Config = Config.empty) : Rule(config) {
...
+            else ->
+                report(CodeSmell(issue, Entity.from(this), noAbstractMember))
         }
     }
 
-    private fun KtClass.hasConstructorParameter() = primaryConstructor?.valueParameters?.isNotEmpty() == true
-
-    private inner class NamedClassMembers(val klass: KtClass, val members: List<KtNamedDeclaration>) {
+    private fun KtClass.members() = body?.children?.filterIsInstance<KtCallableDeclaration>().orEmpty() +
+        primaryConstructor?.valueParameters?.filter { it.hasValOrVar() }.orEmpty()
```
Comment (chao2zhang) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt:107]: For future readers: This line of change is the fix.

**Review by chao2zhang — APPROVED** [review]
