### PR TITLE
ElseCaseInsteadOfExhaustiveWhen - Add ignoredSubjectTypes config key (#5623)

### LINKED ISSUE #5623: ElseCaseInsteadOfExhaustiveWhen config to fail when there's only one unused type/value
I tried enabling ElseCaseInsteadOfExhaustiveWhen but I had way too many violations, and most of them were intentional (e.g. there's a Result type that has Success type and a bunch of failure types, and I only want to know if it was a success or failure, and don't care about the specific failure).

However, I found a few cases where I intended to use an exhaustive when, but I either missed a type, or didn't handle null, and used else instead.

I think it would be helpful if there was a config (or separate rule) that would allow an else in a when, unless there was only one more type that has to be handled (or null).

### PR DESCRIPTION
**Pull request by mmorozkov**
A new `ignoredSubjectTypes` property with an empty default value was introduced. It can be configured with a list of subject types fully qualified names which should be ignored by the `ElseCaseInsteadOfExhaustiveWhen` rule.

Fixes #5623

### CODE REVIEW

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt [hunk 1]
```diff
@@ -59,6 +62,9 @@ class ElseCaseInsteadOfExhaustiveWhen(config: Config = Config.empty) : Rule(conf
         Debt.FIVE_MINS
     )
 
+    @Configuration("List of subject types fully qualified names which should be ignored")
```
Comment (cortinico) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt:65]:
```suggestion
    @Configuration("List of fully qualified types which should be ignored for when expressions with a subject. Example 'kotlinx.serialization.json.JsonObject`")
```

**Review by cortinico — APPROVED** [review]
LGTM 👍

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt (hunk 1 above)
Comment (mmorozkov) [reply detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt]: Thanks, accepted the suggested changes!

**Comment by G00fY2** [comment]
@mmorozkov I initially created this rule and I really like the addition in this PR. The new config property is especially useful for `when` statements with a sealed class subject that represent the success and specific error states. We have something similar in our project and currently use a lot of suppress annotations.

LGTM

**Comment by mmorozkov** [comment]
@cortinico
What are the next steps? Is there anything on me that blocks this PR to be merged?

File: detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt [hunk 2]
```diff
@@ -70,6 +79,10 @@ class ElseCaseInsteadOfExhaustiveWhen(config: Config = Config.empty) : Rule(conf
         if (whenExpression.elseExpression == null) return
 
         val subjectType = subjectExpression.getType(bindingContext)
+        if (ignoredSubjectTypes.contains(subjectType?.fqNameOrNull().toString())) {
```
Comment (BraisGabin) [inline detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/ElseCaseInsteadOfExhaustiveWhen.kt:82]: nit: 
```suggestion
        if (ignoredSubjectTypes.contains(subjectType?.fqNameOrNull()?.toString())) {
```

I don't know what `contains` thinks about `null`. But checking for `"null"` doesn't seem 100% correct.

**Comment by BraisGabin** [comment]
Could you check comment? Once that is addressed I think that this is good to go.

**Comment by mmorozkov** [comment]
> Could you check comment? Once that is addressed I think that this is good to go.

@BraisGabin Done!

**Comment by schalkms** [comment]
@BraisGabin anything left to do there? Otherwise, we should get this merged for inclusion in the detekt next version.

**Comment by mmorozkov** [comment]
@BraisGabin @schalkms @cortinico guys is there anything that block this one from being merged?

**Comment by schalkms** [comment]
@mmorozkov No blockers left. I'll merge this. If @BraisGabin has anything to add, we will create a new PR.
Btw, sorry for the delay. That shouldn't have happened.
