### PR TITLE
Drop (most) Groovy DSL tests

### LINKED ISSUE #4560: Drop Groovy DSL tests in detekt-gradle-plugin
## Expected Behavior
Efficient test suite. We shouldn't run tests that don't provide any extra assurances about the behaviour of the program. I propose dropping all Groovy DSL tests to improve test run time. The detekt-gradle-plugin test suite is one of the slowest in the project.

## Observed Behavior
Almost all of the Gradle plugin tests are run twice - once using the Groovy DSL, again using the Kotlin DSL.

## Steps to Reproduce
N/A

## Context
As far as I'm aware, the Gradle Kotlin DSL is always more strict than the Groovy DSL, with a couple of exceptions. This suggests that testing using Kotlin DSL only would be sufficient.

The exceptions are:
* [Calling Kotlin extension functions from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#static_extensions) requires different syntax. This issue can be avoided by avoiding extension functions entirely. The plugin doesn't currently have any as part of its public API.
* [Calling Kotlin functions with named arguments from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#calling_kotlin_from_groovy) requires use of positional parameters, and can't be called with named arguments from Groovy. I don't believe there are any such functions as part of the plugin's public API.
* [Calling Kotlin functions with default arguments from Groovy](https://docs.gradle.org/7.3.3/userguide/kotlin_dsl.html#calling_kotlin_from_groovy). Values must be passed for all parameters. Again, I'm not aware of any such public functions in the detekt plugin.

We may be able to add custom detekt rules to prevent this occurring, though I don't think that should be a blocker.

Otherwise, Kotlin is more strict. From https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts:
* Kotlin requires double quotes for all strings. In Groovy single quoted strings are also acceptable.
* Kotlin requires parentheses when invoking functions. In Groovy it's optional.
* Kotlin requires the `=` assignment operator when assigning properties. In Groovy it's optional.

When [applying plugins](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#applying_plugins), applying the plugin with `plugins {}` block means statically typed accessors will be available in the build script. This is the case in all current Kotlin DSL tests to guarantee the plugin is behaving correctly, with the exception of `DetektJvmSpec` which uses the `apply` method. As long as functional tests are covering all plugin behaviour this will not become a problem.

When [configuring plugins](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#configuring-plugins), the Kotlin DSL will be difficult to work with if any Groovy dynamic features are used. None are currently used.

When [applying configurations & dependencies](https://docs.gradle.org/7.3.3/userguide/migrating_from_groovy_to_kotlin_dsl.html#configurations-and-dependencies), the `plugins {}` block is required to generate configuration accessors (`detektPlugins` and `detekt`) in Kotlin DSL.

When [using the Provider API](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties), the `set()` method on the property needs to be used instead of `=` when using Kotlin DSL.

### PR DESCRIPTION
**Pull request by 3flex**
Closes #4560

There's a new Groovy DSL test in `DetektTaskGroovyDslSpec` which covers the entire DSL for the extension and the three detekt tasks. It doesn't run the task since many files etc. won't be accessible. Instead, the `:help` task is run, which compiles the build files. Using `tasks.create` for these tasks means the tasks will be created & configured even though they're not run.

### CODE REVIEW

File: detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/report/ReportMergeSpec.kt [hunk 1]
```diff
@@ -20,52 +20,52 @@ class ReportMergeSpec {
...
                         ${builder.gradleSubprojectsApplyPlugins}
-                        |apply plugin: 'java-library'
+                        |plugins.apply("java-library")
                     """.trimMargin()
                 )
             }
             val mainBuildFileContent: String = """
                 |plugins {
-                |    id "io.gitlab.arturbosch.detekt" apply false
+                |    id("io.gitlab.arturbosch.detekt")
```
Comment (3flex) [inline detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/report/ReportMergeSpec.kt:44]: This is the only behaviour change I had to introduce (here, and again in a later test in this class).

Because of the way Gradle generates type-safe accessors for extensions provided by plugins it's necessary to apply the plugin to the root project so that the detekt extension can be used later in the `subprojects` block. This doesn't impact the behaviour of the test itself though.

**Review by BraisGabin — APPROVED** [review]

File: detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektMultiplatformSpec.kt [hunk 2]
```diff
@@ -148,12 +148,12 @@ class DetektMultiplatformSpec {
                     1,
                     buildFileContent = """
                         plugins {
-                            id "kotlin-multiplatform"
-                            id "com.android.library"
-                            id "io.gitlab.arturbosch.detekt"
+                            id("kotlin-multiplatform")
```
Comment (cortinico) [inline detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektMultiplatformSpec.kt:151]: nit: Those could become a `kotlin("multiplatform")` and so on with Kotlin DSL

File: detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektJvmSpec.kt [hunk 3]
```diff
@@ -68,11 +68,11 @@ class DetektJvmSpec {
         inner class `report location set on extension & task` {
             val gradleRunner = DslGradleRunner(
                 projectLayout = ProjectLayout(numberOfSourceFilesInRootPerSourceDir = 1),
-                buildFileName = "build.gradle",
+                buildFileName = "build.gradle.kts",
                 mainBuildFileContent = """
                     plugins {
-                        id "org.jetbrains.kotlin.jvm"
-                        id "io.gitlab.arturbosch.detekt"
+                        id("org.jetbrains.kotlin.jvm")
```
Comment (cortinico) [inline detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/DetektJvmSpec.kt:74]: Same here with `kotlin("jvm")`

**Review by cortinico — APPROVED** [review]
LGTM
