### PR TITLE
MultilineLambdaItParameter: fix false positive for one-line statements with a lambda argument

### LINKED ISSUE #5504: MultilineLambdaItParameter: false positive for one-line statements with a lambda argument
## Steps to Reproduce

```kotlin
@Nested
inner class `single parameter, single-line lambda` {
    @Test
    fun `does not report when statement has one-line lambda argument`() {
        val code = """
        fun f() {
            val digits = 1234.let {
                check(it > 0) { println(it) }
            }
        }
        """.trimIndent()
        val findings = subject.compileAndLintWithContext(env, code)
        assertThat(findings).isEmpty()
    }
}
```

## Context
https://github.com/detekt/detekt/pull/5397#issuecomment-1302776667

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #5504

### CODE REVIEW

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt [hunk 1]
```diff
@@ -106,4 +110,9 @@ class MultilineLambdaItParameter(val config: Config) : Rule(config) {
             }
         }
     }
+
+    private fun KtExpression.hasNoLineBreak() = !textContains('\n')
```
Comment (TWiStErRob) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:114]: You're assuming file separators, which will work for most, but some might use `\r` only.
Is it possible to get the beginning/ending line number of the PsiElement and calculate how many lines it is?

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt [hunk 2]
```diff
@@ -171,6 +189,19 @@ class MultilineLambdaItParameterSpec(val env: KotlinCoreEnvironment) {
...
+            val findings = subject.compileAndLintWithContext(env, code)
+            assertThat(findings).isEmpty()
+        }
+
+        @Test
+        fun `does not report when statement has one-line lambda argument`() {
+            val code = """
+            fun f() {
+                val digits = 1234.let {
+                    check(it > 0) { println(it) }
```
Comment (TWiStErRob) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt:203]: Which `it` is this test targeting? it's unclear what the goal of the test is, could you please clarify it?

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt [hunk 3]
```diff
@@ -129,6 +129,24 @@ class MultilineLambdaItParameterSpec(val env: KotlinCoreEnvironment) {
             val findings = subject.compileAndLintWithContext(env, code)
             assertThat(findings).hasSize(1)
         }
+
+        @Test
+        fun `does not report when statement has no nested statements`() {
```
Comment (TWiStErRob) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt:134]: is there a positive test for this? for example `reports when statement has nested statements`?

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt [hunk 4]
```diff
@@ -76,8 +78,10 @@ class MultilineLambdaItParameter(val config: Config) : Rule(config) {
 
     override fun visitLambdaExpression(lambdaExpression: KtLambdaExpression) {
         super.visitLambdaExpression(lambdaExpression)
-        val size = lambdaExpression.collectDescendantsOfType<KtBlockExpression>().sumOf { it.statements.size }
-        if (size <= 1) return
+
+        val statements = lambdaExpression.bodyExpression?.statements.orEmpty().ifEmpty { return }
+        val single = statements.singleOrNull()
+        if (single != null && (single.hasNoLineBreak() || single.hasNoStatements())) return
```
Comment (TWiStErRob) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:84]: It feels like semantically this might be cleaner (return early + renames), but up to you:
```suggestion
        val statement = statements.singleOrNull() ?: return
        if (statement.isSingleLine() || statement.hasNoSubStatements()) return
```

**Comment by TWiStErRob** [comment]
Amazingly fast response @t-kameyama 👏🏻!

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt (hunk 1 above)
Comment (t-kameyama) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:114]: Line separators are converted to `\n`.

https://github.com/detekt/detekt/blob/ec6cd40a6fa013c3f2dc4ce8343c4f9a1bd4d334/detekt-parser/src/main/kotlin/io/github/detekt/parser/KtCompiler.kt#L33

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt (hunk 3 above)
Comment (t-kameyama) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt:134]: https://github.com/detekt/detekt/blob/993cb9c255e5f60e41b075476e670fd4e0e4c63b/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt#L118-L131

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt (hunk 4 above)
Comment (t-kameyama) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:84]: > val statement = statements.singleOrNull() ?: return

We can't return here because we need to flag multi-line cases.

Comment (TWiStErRob) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:84]: Oh, have to remember to expand the code below the changed lines. Agreed. Please consider renames anyway.

**Review by TWiStErRob — APPROVED** [review]

**Comment by TWiStErRob** [comment]
cc @eygraber

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt [hunk 5]
```diff
@@ -121,14 +121,32 @@ class MultilineLambdaItParameterSpec(val env: KotlinCoreEnvironment) {
...
+            val code = """
+            data class Foo(val x: Int, val y: Int)
+            
+            fun f(i: Int?) {
+                val foo = i?.let {
+                    Foo(
+                        x = it,
```
Comment (eygraber) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt:141]: I'm a little less sure about this case, since it's multiline and the `it` isn't the first line.

Not sure if the example is too generic, but I'm trying to look at this test through the lens of a reader not familiar with the code, and it's not immediately clear to me what the `it` represents here. Although I could think of examples where it is clear.

**Review by eygraber — APPROVED** [review]
Thanks for the quick response!

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt (hunk 1 above)
Comment (TWiStErRob) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt:114]: Hmm, a related thought: you're assuming here that Detekt compiles the PSI, but what if it's run in a different environment? https://github.com/detekt/detekt/pull/5492 at that point all assumptions about line breaks will fail in Detekt rules. cc @3flex

I think checking the line numbers to detect single line is still the most versatile solution.

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt (hunk 5 above)
Comment (chao2zhang) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt:141]: Agree with @eygraber . The following block is non-compliant according to the kDoc.

```
 val digits = 1234.let { it ->
      println(it)
      listOf(it)
 }
```

Let's keep the behavior to be consistent with the spec name `MultilineLambdaItParameter`

**Review by cortinico — APPROVED** [review]
