### PR TITLE
Fix ReturnCount false positive when excludeReturnFromLambda is enabled

### LINKED ISSUE #5341: ReturnCount false positive on lambda returns
## Context
According to the (default) configuration lambda returns should be excluded (be them labeled or not). It might be also to do with nesting, not sure.

## Expected Behavior
No flagging.

## Observed Behavior
Flagged with ReturnCount = 3 (there are 4 returns: 2 in lambdas, 2 outside lambdas, 2 labeled).

## Steps to Reproduce
```kotlin
    @Test fun `function with mix of labeled returns should not count lambdas`() {
        val code = """
            fun transform(flag: Boolean, data: List<List<String>>): String {
                if (data.isEmpty()) return "empty"
                val intermediateResult = data.flatMap { list ->
                    val partial = list.flatMap inner@{ str ->
                        if (flag) {
                            return@inner emptyList()
                        }
                        str.toCharArray().toList()
                    }
                    return@flatMap partial.subList(0, partial.size / 2)
                }
                return intermediateResult.toCharArray().concatToString()
            }
        """.trimIndent()

        val findings = ReturnCount(
            TestConfig(
                mapOf(
                    // https://github.com/detekt/detekt/blob/v1.21.0/detekt-core/src/main/resources/default-detekt-config.yml#L626-L632
                    MAX to "2",
                    EXCLUDE_LABELED to "false",
                    EXCLUDE_RETURN_FROM_LAMBDA to "true",
                    EXCLUDE_GUARD_CLAUSES to "false",
                )
            )
        ).compileAndLint(code)
        assertThat(findings).isEmpty()
    }
```

## Your Environment

* Version of detekt used: 1.21.0

### PR DESCRIPTION
**Pull request by sanggggg**
Fixes #5341

When excludeReturnFromLambda is enabled, then ignore every labeled return **in** lambda block.

There can be some extra cases like below, which may go against `excludeReturnFromLambda`'s general purpose. (do not count return **for** lambda)

```kotlin
fun asdf() {
  kotlin.run {
    return@asdf // do not counted when if excludeReturnFromLambda is enabled.
  }
}
```

But for a clear definition of the `excludeReturnFromLambda` (_if the labeled return from a lambda should be ignored_), I excluded it.

### CODE REVIEW

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt [hunk 1]
```diff
@@ -65,7 +64,7 @@ class ReturnCount(config: Config = Config.empty) : Rule(config) {
     @Configuration("if labeled return statements should be ignored")
     private val excludeLabeled: Boolean by config(false)
 
-    @Configuration("if labeled return from a lambda should be ignored")
+    @Configuration("if labeled return from a lambda should be ignored (takes precedence over excludeLabeled.")
```
Comment (cortinico) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt:67]:
```suggestion
    @Configuration("if labeled return from a lambda should be ignored (takes precedence over excludeLabeled).")
```

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt [hunk 2]
```diff
@@ -113,11 +112,9 @@ class ReturnCount(config: Config = Config.empty) : Rule(config) {
...
         val label = this.labeledExpression
         if (label != null) {
-            return this.parentsOfTypeUntil<KtCallExpression, KtNamedFunction>()
-                .map { it.calleeExpression }
-                .filterIsInstance<KtNameReferenceExpression>()
-                .map { it.text }
-                .any { it in label.text }
+            return this.parentsOfTypeUntil<KtLambdaExpression, KtNamedFunction>()
+                .none()
+                .not()
```
Comment (cortinico) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt:117]: .none().not() is sort of confusing here. Can we rewrite with any or count() >= 1

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt (hunk 1 above)
Comment (sanggggg) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt]: On second thought, the configurations for excluding seem to be `or` conditions. (The added explanation is only making more confusion for the user). So I revert it.

[1b806d8](https://github.com/detekt/detekt/pull/5459/commits/1b806d81d38b8544278bc3e6e551ac1e01352b8a)

**Review by BraisGabin — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt (hunk 2 above)
Comment (TWiStErRob) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt]: `.count()` will unnecessarily materialize the sequence. `.any()` returns a Boolean and will only materialize at most one element of the sequence.

Comment (BraisGabin) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt]: Wouldn't it be `isNotEmpty`?

Comment (sanggggg) [reply detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ReturnCount.kt]: [540634e](https://github.com/detekt/detekt/pull/5459/commits/540634ee78611a09886d9c01ea038e293711c747)
