### PR TITLE
Fix false negative for UseRequire when thrown in conditional block

### LINKED ISSUE #5125: UseRequire: false negative with braces
**While fixing please check related rules for the same problem: (e.g. UseRequireNotNull, UseCheckOrError, UseCheckNotNull).**

## Expected Behavior
Report on:
```kotlin
if (numColors < 1) {
	throw IllegalArgumentException("numColors must be 1 of greater")
}
```

## Observed Behavior
Zzzzzzzz, only reports on:
```kotlin
if (numColors < 1)
	throw IllegalArgumentException("numColors must be 1 of greater")
```

## Steps to Reproduce
```kotlin
private fun updateNumColors(numColors: Int) {
	if (numColors < 1) {
		throw IllegalArgumentException("numColors must be 1 of greater") // should be reported
	}
	println(numColors)
}
```
(remove `if`'s braces to get a violation)

## Context
Code formatting rule automatically adds braces (because it's good practice), braces should be supported with these awesome new rules.

## Your Environment

* Version of detekt used: 1.21.0
* Version of Gradle used (if applicable): 7.5
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/72/files

### PR DESCRIPTION
**Pull request by marschwar**
Fixes #5125

### CODE REVIEW

File: detekt-psi-utils/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/ThrowExtensionsSpec.kt [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+    private fun verifyThrowExpression(
+        @Language("kotlin") code: String,
+        throwingAssertions: KtThrowExpression.() -> Unit
+    ) {
+        val ktFile = compileContentForTest(code)
+        val ktThrowExpression = ktFile.findDescendantOfType<KtThrowExpression>()
+        assertThat(ktThrowExpression)
+            .withFailMessage("no throw expression found")
+            .isNotNull
+        return throwingAssertions(ktThrowExpression!!)
```
Comment (BraisGabin) [inline detekt-psi-utils/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/ThrowExtensionsSpec.kt:128]:
```suggestion
        throwingAssertions(ktThrowExpression!!)
```

**Review by BraisGabin — APPROVED** [review]

**Review by schalkms — APPROVED** [review]
