### PR TITLE
UnusedPrivateMember: don't report parameters in expect/actual functions

### LINKED ISSUE #2636: UnusedPrivateMembers on expect class
## Expected Behavior
Function members **should not** be reported for `except class`

## Observed Behavior
Functions members are reported for `expect class`

## Steps to Reproduce
// _DetektTest.kt
```kotlin
expect class DetektTest  {
    fun test(i: Int)
}
```
* write `actual` declarations that **uses** the param `i`
* run Detekt on CLI and notice the following report:
`UnusedPrivateMember - [i] at ~/_DetektTest.kt:2:14`

## Context
none

## Your Environment
* Version of detekt used: **1.8.0**
* Version of Gradle used (if applicable): **6.3 stable**
* Operating System and version: **macOS 10.15.4 (19E287)**
* Link to your project (if it's a public repository): https://github.com/4face-studi0/Covid19

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #2636

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMemberSpec.kt [hunk 1]
```diff
@@ -55,6 +55,32 @@ class UnusedPrivateMemberSpec : Spek({
         }
     }
 
+    describe("expect functions") {
+
+        it("should not report parameters in expect functions") {
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMemberSpec.kt:60]: What happens when I just write an `expect fun` not inside a class? Unused parameters should not reported for this case. Maybe we should add a test case for quality and coverage reasons.
