### PR TITLE
Ignore private operators when we don't have ContextBingding in UnusedPrivateMember

### LINKED ISSUE #4242: UnusedPrivateMember false positive with operator `in`
## Expected Behavior

```kotlin
val isInside = "bar" in listOf("foo".toRegex())

private operator fun Iterable<Regex>.contains(a: String): Boolean {
    return any { it.matches(a) }
}
```

The extension function should not be flagged because it's used.

## Context
You can look at #4221. I found the issue there. In this commit: https://github.com/detekt/detekt/pull/4241/commits/59f97d9f92b74b22a3b94f8b4690235c8f616124

## Your Environment
* Version of detekt used: main - 1.19.0-RC1

### LINKED ISSUE #4435: UnusedPrivateMember - [invoke]: False positive: Used by public member function
## Expected Behavior
no issue

## Observed Behavior
`UnusedPrivateMember - [invoke] at /Users/philipwedemann/invokeFalsePositive/src/main/kotlin/Test.kt:2:5`

## Steps to Reproduce
`./gradlew detekt`

```kt
object Test {
    private operator fun invoke(i: Int): Int = i

    fun answer() = Test(1)
}

val answer = Test.answer()
```
See also the attached reproducer project
## Context
I adopt the code style from kotlinx.coroutines, which uses this constructor like function to emulate a constructor for an interface:
```kt
interface MutableStateFlow { }
fun MutableStateFlow(initValue: t) { }
```
Using this code style for the `invoke` function and combine it with `object`s results into some kind of namespaces.
## Your Environment

* Version of detekt used: 1.19
* Version of Gradle used: 7.3.3
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/rhwzv6cdovkwe
* Operating System and version: macOS 12.1
* Link to your project (if it's a public repository):
[invokeFalsePositive.zip](https://github.com/detekt/detekt/files/7799166/invokeFalsePositive.zip)

### PR DESCRIPTION
**Pull request by BraisGabin**
Maintaining mixed rules is really painful: #2994.

Note: the change seems big but I just added the `filterNot` on the top. The problem is that with the reformat git thinks that all is new.

fixes #4242
#4435 is related. This will fix the false positives without type solving. But we still have false positives with type solving.

### CODE REVIEW

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMemberSpec.kt [hunk 1]
```diff
@@ -1028,6 +1029,19 @@ class UnusedPrivateMemberSpec : Spek({
             assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
         }
 
+        it("does not report used plus operator without type solving - #4242") {
```
Comment (schalkms) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMemberSpec.kt:1032]: Maybe we should add a test case for the issue described in #4435 as well. What do you think?

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMember.kt [hunk 2]
```diff
@@ -101,54 +101,60 @@ private class UnusedFunctionVisitor(
...
-                            else -> emptyList()
-                        }
-                        val containingReferences = if (functionNameAsName == OperatorNameConventions.CONTAINS) {
-                            listOf(KtTokens.IN_KEYWORD, KtTokens.NOT_IN).flatMap {
-                                functionReferences[it.value].orEmpty()
+        return functionDeclarations
+            .filterNot { (_, functions) ->
+                // Without a binding context we can't know if an operator is called. So we ignore it to avoid
+                // false positives. More context at #4242
+                bindingContext == BindingContext.EMPTY && functions.any { it.isOperator() }
```
Comment (schalkms) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateMember.kt:108]: Good!

**Review by schalkms — APPROVED** [review]
