### PR TITLE
LongMethod: disregard params in method definition

### LINKED ISSUE #2804: LongMethod should not consider parameters while calculating the number of lines
## Expected Behavior

LongMethod should consider the method definition without the input parameters.
Example:
If `LongMethod` threshold is set to 7, then the below method shouldn't be tagged as the method implementation is actually 3 loc and detekt already has `LongParameterList` to check the param list
```
fun fetch(
        user: User,
        org: Org,
        @QueryValue startDate: String,
        @QueryValue endDate: String
    ) {
        val data = service1.get(startDate, endDate, context.user, context.org)
        val moreData = service2.get(startDate)
        ok(mapOf("data" to data+moreData))
    }
```
## Observed Behavior

The above snippet of code gets tagged with `LongMethod` code smell

## Steps to Reproduce

#2806

## Context

More LongMethod code smell then expected

## Your Environment

* Version of detekt used:1.9.1
* Version of Gradle used (if applicable):6.1.1
* Operating System and version:macOS 10.15.5
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by niraj8**
Fixes #2804

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 1]
```diff
@@ -44,5 +45,41 @@ class LongMethodSpec : Spek({
...
             assertThat(subject.compileAndLint(code)).isEmpty()
         }
+
+        it("should not find too long method with params on newlines") {
+            val code = """
+                fun methodWithParams( // 4 lines
+                    param1: String,
+                    param2: String,
+                    @QueryValue startDate: String,
+                    @QueryValue endDate: String
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:55]: With this modification the code snippet actually compiles.
```suggestion
                    startDate: String,
                    endDate: String
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 2]
```diff
@@ -44,5 +45,41 @@ class LongMethodSpec : Spek({
...
+            assertThat(subject.compileAndLint(code)).isEmpty()
+        }
+
+        it("should find too long method with params on newlines") {
+            val code = """
+                fun longMethodWithParams( // 5 lines
+                    param1: String,
+                    param2: String,
+                    @QueryValue startDate: String,
+                    @QueryValue endDate: String
```
Comment (schalkms) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:71]:
```suggestion
                    startDate: String,
                    endDate: String
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt (hunk 1 above)
Comment (niraj8) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:55]: Can you check the tagged issue, please?

Comment (niraj8) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt]: I get it now. Thanks!

File: detekt-metrics/src/main/kotlin/io/github/detekt/metrics/LinesOfCode.kt [hunk 3]
```diff
@@ -40,7 +41,7 @@ fun ASTNode.tokenSequence(skipTreesOf: Set<Class<out PsiElement>>): Sequence<AST
 }
 
 fun KtElement.linesOfCode(inFile: KtFile = this.containingKtFile): Int =
-    node.tokenSequence(comments)
+    node.tokenSequence(comments + KtParameterList::class.java)
```
Comment (arturbosch) [inline detekt-metrics/src/main/kotlin/io/github/detekt/metrics/LinesOfCode.kt:44]: This is a generic function so we shouldn't just suppress any elements here.
Rather lets call `linesOfCode` with a different elelement.

In `LongMethod:L64` instead of `function.linesOfCode` lets use it's body/block if not null.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 4]
```diff
@@ -44,5 +45,110 @@ class LongMethodSpec : Spek({
...
+                        println()
+                    }
+                }
+            """
+
+            val findings = subject.compileAndLint(code)
+
+            assertThat(findings).hasSize(2)
+            assertThat(findings).hasTextLocations("longMethod", "nestedLongMethod")
+            assertThat(findings[0] as ThresholdedCodeSmell).hasValue(5)
```
Comment (niraj8) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:125]: I want to filter a code-smell for a specific method in the code. 
How can I do this?

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 5]
```diff
@@ -44,5 +45,110 @@ class LongMethodSpec : Spek({
...
+
+            assertThat(findings).hasSize(1)
+            assertThat(findings[0] as ThresholdedCodeSmell).hasValue(8)
+        }
+
+        it("should find two long methods with params on separate lines") {
+            val code = """
+                fun longMethod(
+                    param1: String
+                ) { // 5 lines
```
Comment (niraj8) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:106]: Value for top-level method is calculated as **7** because of [this](https://github.com/niraj8/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethod.kt#L72)

```
?.let { functionToLinesCache[function] = lines - it }
``` 

How should I proceed?

File: detekt-metrics/src/main/kotlin/io/github/detekt/metrics/LinesOfCode.kt (hunk 3 above)
Comment (niraj8) [reply detekt-metrics/src/main/kotlin/io/github/detekt/metrics/LinesOfCode.kt]: Thanks @arturbosch for the review
I made some changes according to the above review.
I had some questions on how to proceed, added inline comments for this.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt (hunk 5 above)
Comment (niraj8) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:106]: Value(line count) is calculated for a method by subtracting the values for its nested methods.

Because the new calculation ignores the lines with the parameter list, those lines are not taken into account for the top-level method.

I would need some help in figuring out how to deal with this.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt (hunk 4 above)
Comment (arturbosch) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:125]: You want to get the `KtNamedFunction` node to test somehting?  -> `finding.entity.ktElement`.
Testing the text locations should be enought -> `hasTextLocations(line to column)`.

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt (hunk 5 above)
Comment (arturbosch) [reply detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:106]: You could try to decide if this current KtNamdFunction is nested or not and use `function.linesOfCode` or `function.body.linesOfCode` based on this criteria:

```kotlin
val isNested = function.getStrictParentOfType<KtNamedFunction>() != null

val entity = if (isNested) {
    function.bodyBlockExpression ?: function.bodyExpression
} else {
    function    
}
entity.linesOfCode()
...
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 6]
```diff
@@ -44,5 +45,108 @@ class LongMethodSpec : Spek({
...
+                        println()
+                        println()
+                        println()
+                    }
+                }
+            """
+
+            val findings = subject.compileAndLint(code)
+
+            assertThat(findings).hasSize(1  )
```
Comment (cortinico) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:147]:
```suggestion
            assertThat(findings).hasSize(1)
```

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt [hunk 7]
```diff
@@ -44,5 +45,108 @@ class LongMethodSpec : Spek({
...
+            assertThat(findings).hasTextLocations( "nestedLongMethod")
```
Comment (cortinico) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/LongMethodSpec.kt:148]:
```suggestion
            assertThat(findings).hasTextLocations("nestedLongMethod")
```
