### PR TITLE
Only print paths of reports when detektion fails

### LINKED ISSUE #8558: Refactor how we notify the paths of our reports
## Expected Behavior
The reports doesn't change `Detektion` as it is the output value of detekt and the reports should only render that output. They should modify it.

## Current Behavior
`OutputFacade` adds a notification to `Detektion`

## Context
#6879

We can't just "remove" those notifications as we would lose the feature of letting our users know where the reports are stored. And an easy way to click over them on the console. We need to keep the behavior but using a different implementation.

I'm thinking about mimic the behavior of JUnit. They only print the output of the report if there is a failing test. ~That would move the responsability to the runners (cli and gradle-plugin) because they are the ones that know if the run of detekt failed or not (we have configurations to allow issues and pass detekt).~

~I also like this idea because once `Detektion` is serializable we can remove old the report handling out of `:detekt-core`.~

Edit: I didn't need to move anything outside `core` to archive this. Maybe we need to move that code to the runners but we don't need to make it now.

### LINKED ISSUE #8592: Show report paths when detekt check fails
## Expected Behavior
detekt print the paths of the reports when the check fails on the console so I can see them easily. But it doesn't print those paths when there are no issues.

## Observed Behavior
Right now I only have 2 options or detekt never prints the paths (excluding `NotificationReport`) or it prints them always.

## Context
When everything works as expected I want a quiet build. Gradle should run with 0 output. But when the task fails I want the paths of the generated reports so I have all the information to solve the problem.

There is already an implementation of this at #8560 but I'm creating this issue so we can talk about this behavior change.

### PR DESCRIPTION
**Pull request by BraisGabin**
Closes #8558
Closes #8592

These PR changes the behavior of detekt in two different but related ways:
1. We don't use `NotificationReport` to notify the paths of our reports, we write them directly to the output. Before you could exclude `NotificationReport` and you would never see this output.
   - This helps with #6879
2. We print the paths only and only if there are issues. This mimics the behavior of JUnit. Before we were always reporting them if you had `NotificationReport` enabled (no-excluded).

I think that this is a clear improvement. In general detekt always passes so having the paths of each report of each module is REALLY noisy. You want no output when everything works so you disable `NotificationReport`. But when there are issues you want information. And the paths of the reports in the console are really handy so you can click over them.

### CODE REVIEW

**Review by schalkms — COMMENTED** [review]
I'm not sure about this change.
I think we need to check if the documentation clarifies the **old** behaviour. If it does, it should be changed. If it does not, it should be documented.

I feel like it's a fundamental change in detekt's reporting behaviour, even more so for the long term user base.

**Comment by BraisGabin** [comment]
> I'm not sure about this change. I think we need to check if the documentation clarifies the **old** behaviour. If it does, it should be changed. If it does not, it should be documented.
> 
> I feel like it's a fundamental change in detekt's reporting behaviour, even more so for the long term user base.

I created #8592 so we can talk if this behavior change is good or not.

**Comment by BraisGabin** [comment]
Can I get some attention here or at #8592? This will unlock some other issues.

**Comment by BraisGabin** [comment]
Can I get some attention here or at #8592? This will unlock some other issues.

File: detekt-core/src/test/kotlin/dev/detekt/core/reporting/OutputFacadeSpec.kt [hunk 1]
```diff
@@ -83,7 +92,7 @@ class OutputFacadeSpec {
         }
 
         assertThatCode {
-            spec.withSettings { OutputFacade(this).run(defaultResult) }
+            spec.withSettings { OutputFacade(this, true).run(defaultResult) }
```
Comment (schalkms) [inline detekt-core/src/test/kotlin/dev/detekt/core/reporting/OutputFacadeSpec.kt]: From my perspective, this boolean parameter does not look very readable. I would suggest to
1. Use a more descriptive enum `Reports.shown, Reports.hidden`
2. Move this parameter to `run()` with default `.hidden`
What do you think?

**Review by schalkms — APPROVED** [review]
👍
Just one minor comment...

File: detekt-core/src/test/kotlin/dev/detekt/core/reporting/OutputFacadeSpec.kt (hunk 1 above)
Comment (BraisGabin) [reply detekt-core/src/test/kotlin/dev/detekt/core/reporting/OutputFacadeSpec.kt]: That have sense. What do you think about something like this? e786ed40749615b59c6328c036b195851393450d

**Review by schalkms — APPROVED** [review]
Ty 👍
