### PR TITLE
UnusedPrivateClass: fix false negative with import directives

### LINKED ISSUE #2816: UnusedPrivateClass: false negative with import directives
## Steps to Reproduce
```kotlin
package com.example

import com.example.C.EFG.EFG1

class C {
    fun test() {
        println(EFG1)
    }

    private enum class E { // false negative
        E1
    }

    private enum class EFG {
        EFG1
    }
}
```

Related: https://github.com/detekt/detekt/pull/2812#discussion_r443204280

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #2816

### CODE REVIEW

File: detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateClassSpec.kt [hunk 1]
```diff
@@ -384,5 +384,29 @@ class UnusedPrivateClassSpec : Spek({
...
+                        E1
+                    }
+
+                    private enum class EFG {
+                        EFG1
+                    }
+                }
+            """
+            val findings = UnusedPrivateClass().lint(code)
+            assertThat(findings).hasSize(1)
```
Comment (cortinico) [inline detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedPrivateClassSpec.kt:409]: Please add also a:
`assertThat(findings).hasSourceLocation(xxx, yyy)`

This will make sure the rule is reporting the correct occurrence.
