### PR TITLE
Consider deprecated rules as inactive when running `allRules`

### LINKED ISSUE #6336: Cannot disable OptionalWhenBraces with warningsAsErrors: true
## Expected Behavior
Should be able to disable deprecated rules, or maybe be disabled by default?

## Observed Behavior
Either have many OptionalWhenBraces violations or
```
Execution failed for task ':...:detekt'.
> Run failed with 1 invalid config property.
        - Property 'style>OptionalWhenBraces' is deprecated. Same functionality is implemented in BracesOnWhenStatements.
```

## Steps to Reproduce
```gradle.kts
detekt {
    allRules = true
}
```
```yaml
config:
  warningsAsErrors: true
style:
  OptionalWhenBraces:
    active: false
```

## Context
I shouldn't have to choose between having a strict build, or having a short configuration file (allRules + overrides), or having a customized detekt config (active: false). I'm fully sure what's going on here, and why this never happened before, but it's a strange situation and I wonder what you guys think about it.

Can you think of a workaround for this apart from disabling `warningsAsErrors`, or listing all the rules explicitly rather than excluding the ones I don't want?

## Your Environment

* Version of detekt used: 1.23.1
* Version of Gradle used (if applicable): 8.3 rc 2
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by marschwar**
(quick) fixes #6336 

**Note: This PR targets the `release/1.x` branch instead of `main`.** 

Following [this suggestion](https://github.com/detekt/detekt/issues/6336#issuecomment-1674944509) I hacked something up that should fix the issue short term. The idea is that all deprecated rules are considered as inactive in case detekt is run with the `allRules` option. We should probably find a better solution for the main branch.

### CODE REVIEW

**Comment by BraisGabin** [comment]
🤔 I'm not sure here. But what will happen if you read the deprecation file? You should be able to extract that list too, right? This way you don't need to hardcode the list of deprecated rules.

**Comment by marschwar** [comment]
>  But what will happen if you read the deprecation file? You should be able to extract that list too, right? This way you don't need to hardcode the list of deprecated rules.

I totally agree. This could be the actual fix for the main branch. This was meant to be a quick fix only in case we want to deliver something quickly. But I guess that still could be done here. I will update the PR.

**Review by BraisGabin — APPROVED** [review]

**Comment by BraisGabin** [comment]
Then this PR should go against 2.0, right?

**Comment by marschwar** [comment]
> Then this PR should go against 2.0, right?

No, it is intended for the 1.x only. For the 2.x I would like to  use #6382.

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/Analyzer.kt [hunk 1]
```diff
@@ -203,3 +208,11 @@ internal fun ProcessingSpec.workaroundConfiguration(config: Config): Config = wi
 
     return declaredConfig ?: getDefaultConfiguration()
 }
+
+internal fun loadDeprecatedRuleIds(): Set<String> {
+    return loadDeprecations().keys
```
Comment (cortinico) [inline detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/Analyzer.kt:213]:
```suggestion
internal fun loadDeprecatedRuleIds(): Set<String> =
    loadDeprecations().keys
```

**Review by cortinico — APPROVED** [review]
Works great for me 👍 Let's merge this so I can prepare `.2`

**Comment by marschwar** [comment]
Fix for 2.0 is #6433.

**Comment by BraisGabin** [comment]
We can merge this, right?

**Comment by cortinico** [comment]
> We can merge this, right?

Yup 👍
