### PR TITLE
Use main-kts artifact to compile test code snippets

### LINKED ISSUE #5739: False negative tests in Detekt project
## Expected Behavior

<details><summary><code>Caused by: javax.script.ScriptException: Error: error: unresolved reference: launch</code></summary>

```
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :detekt-rules-coroutines:processTestResources NO-SOURCE
> Task :detekt-api:processResources NO-SOURCE
> Task :detekt-metrics:processResources NO-SOURCE
> Task :detekt-tooling:processResources NO-SOURCE
> Task :detekt-psi-utils:processResources NO-SOURCE
> Task :detekt-parser:processResources NO-SOURCE
> Task :detekt-test:processResources NO-SOURCE
> Task :detekt-test-utils:processResources NO-SOURCE
> Task :detekt-utils:processResources NO-SOURCE
> Task :detekt-core:processResources UP-TO-DATE
> Task :detekt-report-md:processResources UP-TO-DATE
> Task :detekt-report-txt:processResources UP-TO-DATE
> Task :detekt-rules-coroutines:processResources UP-TO-DATE
> Task :detekt-report-html:processResources UP-TO-DATE
> Task :detekt-report-sarif:processResources UP-TO-DATE
> Task :detekt-report-xml:processResources UP-TO-DATE
> Task :detekt-utils:compileKotlin UP-TO-DATE
> Task :detekt-psi-utils:compileKotlin UP-TO-DATE
> Task :detekt-utils:compileJava NO-SOURCE
> Task :detekt-psi-utils:compileJava NO-SOURCE
> Task :detekt-psi-utils:classes UP-TO-DATE
> Task :detekt-utils:classes UP-TO-DATE
> Task :detekt-utils:jar UP-TO-DATE
> Task :detekt-psi-utils:jar UP-TO-DATE
> Task :detekt-api:compileKotlin UP-TO-DATE
> Task :detekt-parser:compileKotlin UP-TO-DATE
> Task :detekt-parser:compileJava NO-SOURCE
> Task :detekt-api:compileJava NO-SOURCE
> Task :detekt-parser:classes UP-TO-DATE
> Task :detekt-api:classes UP-TO-DATE
> Task :detekt-parser:jar UP-TO-DATE
> Task :detekt-api:jar UP-TO-DATE
> Task :detekt-metrics:compileKotlin UP-TO-DATE
> Task :detekt-report-txt:compileKotlin UP-TO-DATE
> Task :detekt-rules-coroutines:compileKotlin UP-TO-DATE
> Task :detekt-report-xml:compileKotlin UP-TO-DATE
> Task :detekt-test-utils:compileKotlin UP-TO-DATE
> Task :detekt-tooling:compileKotlin UP-TO-DATE
> Task :detekt-rules-coroutines:compileJava NO-SOURCE
> Task :detekt-report-xml:compileJava NO-SOURCE
> Task :detekt-metrics:compileJava NO-SOURCE
> Task :detekt-rules-coroutines:classes UP-TO-DATE
> Task :detekt-metrics:classes UP-TO-DATE
> Task :detekt-test-utils:compileJava NO-SOURCE
> Task :detekt-report-xml:classes UP-TO-DATE
> Task :detekt-test-utils:classes UP-TO-DATE
> Task :detekt-report-txt:compileJava NO-SOURCE
> Task :detekt-report-txt:classes UP-TO-DATE
> Task :detekt-tooling:compileJava NO-SOURCE
> Task :detekt-tooling:classes UP-TO-DATE
> Task :detekt-report-xml:jar UP-TO-DATE
> Task :detekt-test-utils:jar UP-TO-DATE
> Task :detekt-metrics:jar UP-TO-DATE
> Task :detekt-report-txt:jar UP-TO-DATE
> Task :detekt-tooling:jar UP-TO-DATE
> Task :detekt-report-md:compileKotlin UP-TO-DATE
> Task :detekt-report-html:compileKotlin UP-TO-DATE
> Task :detekt-report-sarif:compileKotlin UP-TO-DATE
> Task :detekt-report-sarif:compileJava NO-SOURCE
> Task :detekt-report-md:compileJava NO-SOURCE
> Task :detekt-report-md:classes UP-TO-DATE
> Task :detekt-report-sarif:classes UP-TO-DATE
> Task :detekt-report-html:compileJava NO-SOURCE
> Task :detekt-report-html:classes UP-TO-DATE
> Task :detekt-report-md:jar UP-TO-DATE
> Task :detekt-report-html:jar UP-TO-DATE
> Task :detekt-report-sarif:jar UP-TO-DATE
> Task :detekt-core:compileKotlin UP-TO-DATE
> Task :detekt-core:compileJava NO-SOURCE
> Task :detekt-core:classes UP-TO-DATE
> Task :detekt-core:jar UP-TO-DATE
> Task :detekt-test:compileKotlin UP-TO-DATE
> Task :detekt-test:compileJava NO-SOURCE
> Task :detekt-test:classes UP-TO-DATE
> Task :detekt-test:jar UP-TO-DATE
> Task :detekt-rules-coroutines:compileTestKotlin FROM-CACHE
> Task :detekt-rules-coroutines:compileTestJava NO-SOURCE
> Task :detekt-rules-coroutines:testClasses UP-TO-DATE
> Task :detekt-rules-coroutines:test
Predictive Test Selection: all test classes selected
Picked up JAVA_TOOL_OPTIONS: -Xms32M -Xmx256M -XX:+UseG1GC -D-XX:+PrintCommandLineFlags
WARN: Attempt to load key 'platform.random.idempotence.check.rate' for not yet loaded registry
[com.gradle.enterprise.testdistribution] Test was part of session 2 and ran on a local executor named 'localhost-executor-1' on host 'localhost'.

Given Kotlin code is invalid.
io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
	at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:37)
	at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:23)
	at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
	at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.2/java.util.ArrayList.forEach(ArrayList.java:1540)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.2/java.util.ArrayList.forEach(ArrayList.java:1540)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.2/java.util.ArrayList.forEach(ArrayList.java:1540)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain$c.a(SourceFile:221)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain$c.a(SourceFile:207)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain$c.b(SourceFile:198)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain$c.a(SourceFile:190)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain.a(SourceFile:81)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain.a(SourceFile:72)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.l.a(SourceFile:20)
	at app//com.gradle.enterprise.testdistribution.launcher.forked.LauncherMain.main(SourceFile:57)
Caused by: javax.script.ScriptException: Error: error: unresolved reference: launch
    launch {
    ^
error: suspension functions can be called only within coroutine body
        delay(timeMillis = 1000)
        ^

	at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
	at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
	at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:50)
	at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
	... 84 more




SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() FAILED
    io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:37)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:23)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)
        Caused by:
        javax.script.ScriptException: Error: error: unresolved reference: launch
            launch {
            ^
        error: suspension functions can be called only within coroutine body
                delay(timeMillis = 1000)
                ^
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
            at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:50)
            at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
            ... 3 more
1 test completed, 1 failed
> Task :detekt-rules-coroutines:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':detekt-rules-coroutines:test'.
> There were failing tests. See the report at: file:///P:/projects/contrib/github-detekt/detekt-rules-coroutines/build/reports/tests/test/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 7s
38 actionable tasks: 1 executed, 1 from cache, 36 up-to-date
```

</details>

Note: it actually fails when running this specific test from IDEA.

## Observed Behavior

```
Daemon will be stopped at the end of the build
settings 'github-detekt' has no Warning Mode specified, using a default fallback in init script: --warning-mode=all.
Type-safe project accessors is an incubating feature.

> Configure project :
compile-test-snippets: valueof(GradlePropertyValueSource) -> true -> true

> Task :detekt-rules-coroutines:test
Predictive Test Selection: all test classes selected

Distributed Test Run :detekt-rules-coroutines:test STANDARD_ERROR
    Picked up JAVA_TOOL_OPTIONS: -Xms32M -Xmx256M -XX:+UseG1GC -D-XX:+PrintCommandLineFlags

InjectDispatcherSpec > InjectDispatcher with default config > does not report when dispatcher is used as a constructor parameter() STANDARD_ERROR
    WARN: Attempt to load key 'platform.random.idempotence.check.rate' for not yet loaded registry

BUILD SUCCESSFUL in 33s
54 actionable tasks: 1 executed, 53 up-to-date
```

The build is successful too from IDEA if I run the `:test` task directly without `--tests`.

## Steps to Reproduce
1. Remove the import `import kotlinx.coroutines.launch` from `@Test fun` `no reports when suspend function has no receiver` (i.e. revert https://github.com/detekt/detekt/pull/5716):
```patch
Index: detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt b/detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt
--- a/detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt	(revision 2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b)
+++ b/detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt	(date 1675116072114)
@@ -100,7 +100,6 @@
             val code = """
                 import kotlinx.coroutines.coroutineScope
                 import kotlinx.coroutines.delay
-                import kotlinx.coroutines.launch
                 import kotlin.time.Duration.Companion.seconds
 
                 suspend fun foo() = coroutineScope {
```
2. Run tests with `-Pcompile-test-snippets=true`

Originally discovered by @VitalyVPinchuk running
```shell
gradlew test -Pcompile-test-snippets=true
```
on his machine on an older version of `main` (0123c85b1698ffb78fc6151e7317f55449bb5171), and then I confirmed it on latest `main` (2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b) today.

The issue can be observed with a smaller set of Gradle tasks:
```shell
gradlew :detekt-rules-coroutines:test -Pcompile-test-snippets=true
```
and it even reproduces when we throw everything at it (disable (almost-)all the Gradle goodness):
```shell
gradlew :detekt-rules-coroutines:clean :detekt-rules-coroutines:test -Pcompile-test-snippets=true --no-configuration-cache --no-build-cache --no-daemon --no-watch-fs --no-parallel --console=verbose
```

I also tried to disable `predictiveSelection` by setting an env var `set CI=true` and then running the above, same results.

<details><summary>We tried to debug it a bit, for example seeing what values are seen in Gradle in response to <code>-P</code></summary>

```patch
Index: build-logic/src/main/kotlin/module.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build-logic/src/main/kotlin/module.gradle.kts b/build-logic/src/main/kotlin/module.gradle.kts
--- a/build-logic/src/main/kotlin/module.gradle.kts	(revision 2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b)
+++ b/build-logic/src/main/kotlin/module.gradle.kts	(date 1675115479404)
@@ -23,7 +23,10 @@
 tasks.withType<Test>().configureEach {
     useJUnitPlatform()
     systemProperty("junit.jupiter.testinstance.lifecycle.default", "per_class")
-    val compileTestSnippets = providers.gradleProperty("compile-test-snippets").orNull.toBoolean()
+    val gradleProperty = providers.gradleProperty("compile-test-snippets")
+    val orNull = gradleProperty.orNull
+    val compileTestSnippets = orNull.toBoolean()
+    println("compile-test-snippets: ${gradleProperty} -> ${orNull} -> ${compileTestSnippets}")
     systemProperty("compile-test-snippets", compileTestSnippets)
     testLogging {
         // set options for log level LIFECYCLE
```
it's picked up correctly.

</details>

Note: it does fail from command line too, if I run:
```shell
gradlew :detekt-rules-coroutines:test --tests "io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver" -Pcompile-test-snippets=true
```
so it's only the generic `test` task without `--tests` arg that doesn't behave.

## Context
If we have false negative CI, that means we can't trust our test suite. So this sounds like it could be a big issue.

Because of this issue we had a failing test since 2022-03-23 088eae47c2fd0eefa7d32735738f4dde31246cea which was just recently fixed almost a year later in https://github.com/detekt/detekt/pull/5716 (thanks @atulgpt for finding, [reporting](https://github.com/detekt/detekt/issues/5715) and [fixing](https://github.com/detekt/detekt/pull/5716)).

## Your Environment

* Version of detekt used: latest `main` 2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b
* Version of Gradle used (if applicable): latest `main` 2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Windows 10 Pro 22H2 19045.2486 (@TWiStErRob), Mac OS Ventura 13.2 22D49 (@VitalyVPinchuk)
* Link to your project (if it's a public repository): latest `main` 2afb8a9bbe66f5dc063cb229d7f4ef3dee2ef19b

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #5739

### CODE REVIEW

File: detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt [hunk 1]
```diff
@@ -19,21 +18,6 @@ internal class PooledScriptEngineTest {
             .isInstanceOf(ScriptException::class.java)
     }
 
-    @Test
-    fun `compiling the same type twice leads to a compiler error`() {
```
Comment (TWiStErRob) [inline detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt:23]: Keep with opposite expectation? As a regression test for #5739. Or add one that really tests specifically for #5739.

File: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt [hunk 2]
```diff
@@ -408,6 +408,8 @@ class CanBeNonNullableSpec(val env: KotlinCoreEnvironment) {
         @Test
         fun `does not report on properties of a parameterized type which must be nullable`() {
             val code = """
+                import kotlin.random.Random
```
Comment (TWiStErRob) [inline detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt:411]: Relevant or leftover?

Comment (TWiStErRob) [reply detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/CanBeNonNullableSpec.kt:411]: Ah, a false negative, expand code block...

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt [hunk 3]
```diff
@@ -48,5 +43,8 @@ internal object KotlinScriptEnginePool {
 internal class PooledScriptEngine(private val engine: KotlinJsr223JvmLocalScriptEngine) {
     fun compile(code: String) {
         engine.compile(code)
+
+        // This prevents script compilations from interfering with each other when an engine is reused
+        engine.setBindings(SimpleBindings(), ScriptContext.ENGINE_SCOPE)
```
Comment (TWiStErRob) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:48]: Rather than cleaning up afterwards, could the engine be set up clean *before* use?

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt [hunk 4]
```diff
@@ -48,5 +43,8 @@ internal object KotlinScriptEnginePool {
 internal class PooledScriptEngine(private val engine: KotlinJsr223JvmLocalScriptEngine) {
     fun compile(code: String) {
         engine.compile(code)
```
Comment (TWiStErRob) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]: I got a strange exception chain, is it possible that the first valid failure leaves the memory in an inconsistent state:
```
> Task :detekt-rules-coroutines:test

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() STANDARD_ERROR
    WARN: Attempt to load key 'platform.random.idempotence.check.rate' for not yet loaded registry

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() STANDARD_OUT
    [com.gradle.enterprise.testdistribution] Test was part of session 1 and ran on a local executor named 'localhost-executor-5' on host 'localhost'.

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() FAILED
    io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:21)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)

        Caused by:
        javax.script.ScriptException: Error: error: unresolved reference: launch
            launch {
            ^
        error: suspension functions can be called only within coroutine body
                delay(timeMillis = 1000)
                ^
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
            at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:45)
            at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:27)
            ... 3 more

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > reports when top-level suspend function has explicit FQN CoroutineScope receiver type() STANDARD_OUT
    [com.gradle.enterprise.testdistribution] Test was part of session 1 and ran on a local executor named 'localhost-executor-5' on host 'localhost'.

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > reports when top-level suspend function has explicit FQN CoroutineScope receiver type() FAILED
    org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_0
    File being compiled: (2,32) in /Line_0.kts
    The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:43)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:461)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitScript(KtVisitor.java:78)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:527)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
        at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.registerDeclarations(LazyTopDownAnalyzer.kt:80)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitKtFile(LazyTopDownAnalyzer.kt:98)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:521)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:250)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:237)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitElement(ExceptionWrappingKtVisitorVoid.kt:27)
        at app//org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:521)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:250)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:237)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:203)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.runAnalyzer(ReplCodeAnalyzer.kt:131)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.doAnalyze(ReplCodeAnalyzer.kt:140)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.analyzeReplLine(ReplCodeAnalyzer.kt:117)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.GenericReplCompiler.compile(GenericReplCompiler.kt:81)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:72)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
        at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:45)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:27)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:21)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.reports when top-level suspend function has explicit FQN CoroutineScope receiver type(SuspendFunWithCoro
utineScopeReceiverSpec.kt:61)

        Caused by:
        org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration SCRIPT
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:17)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.findClassDescriptor(LazyDeclarationResolver.kt:88)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.getScriptDescriptor(LazyDeclarationResolver.kt:65)
            at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitScript(LazyTopDownAnalyzer.kt:91)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:527)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
            at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
            at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
            at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:32)
            ... 35 more

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > reports when top-level suspend function has explicit CoroutineScope receiver type() STANDARD_OUT
    [com.gradle.enterprise.testdistribution] Test was part of session 1 and ran on a local executor named 'localhost-executor-5' on host 'localhost'.

SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > reports when top-level suspend function has explicit CoroutineScope receiver type() FAILED
    org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_0
    File being compiled: (3,32) in /Line_0.kts
    The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:43)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:461)
```

Comment (TWiStErRob) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]: repro: as in the issue #5739, remove `launch` import and run all tests in that module.

Comment (TWiStErRob) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]: I also consistently get an OOM on `Task :detekt-rules-style:test` with env `CI=true`:
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 2.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.jetbrains.kotlin.protobuf.SmallSortedMap.entrySet(SmallSortedMap.java:354)
	at org.jetbrains.kotlin.protobuf.FieldSet.iterator(FieldSet.java:201)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite$ExtendableMessage$ExtensionWriter.<init>(GeneratedMessageLite.java:274)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite$ExtendableMessage$ExtensionWriter.<init>(GeneratedMessageLite.java:270)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite$ExtendableMessage.newExtensionWriter(GeneratedMessageLite.java:308)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Function.writeTo(ProtoBuf.java:16235)
	at org.jetbrains.kotlin.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:92)
	at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.packToByteArray(DeserializedMemberScope.kt:246)
	at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.<init>(DeserializedMemberScope.kt:233)
	at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.createImplementation(DeserializedMemberScope.kt:226)
	at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.<init>(DeserializedMemberScope.kt:49)
	at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedPackageMemberScope.<init>(DeserializedPackageMemberScope.kt:44)
	at org.jetbrains.kotlin.load.kotlin.DeserializedDescriptorResolver.createKotlinPackagePartScope(DeserializedDescriptorResolver.kt:72)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:47)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:44)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getKotlinScopes(JvmPackageScope.kt:44)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:58)
	at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:35)
	at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
	at org.jetbrains.kotlin.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(findClassInModule.kt:26)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.computeClassifierDescriptor(TypeDeserializer.kt:269)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.access$computeClassifierDescriptor(TypeDeserializer.kt:29)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer$classifierDescriptors$1.invoke(TypeDeserializer.kt:38)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer$classifierDescriptors$1.invoke(TypeDeserializer.kt:37)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.typeConstructor(TypeDeserializer.kt:162)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:92)
	at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.type(TypeDeserializer.kt:69)
	at org.jetbrains.kotlin.serialization.deserialization.MemberDeserializer.loadProperty(MemberDeserializer.kt:57)
```

and CI concurs: https://github.com/detekt/detekt/actions/runs/4051794203/jobs/6970480395

Comment (TWiStErRob) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]: I'll look for the heapdump later, hope it's there somewhere

Comment (TWiStErRob) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]:
```patch
Subject: [PATCH] helper
---
Index: build-logic/src/main/kotlin/module.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build-logic/src/main/kotlin/module.gradle.kts b/build-logic/src/main/kotlin/module.gradle.kts
--- a/build-logic/src/main/kotlin/module.gradle.kts	(revision e9e91143261caf02303160723e13de60a7ec1c9d)
+++ b/build-logic/src/main/kotlin/module.gradle.kts	(date 1675159999747)
@@ -22,6 +22,7 @@
 
 tasks.withType<Test>().configureEach {
     useJUnitPlatform()
+    jvmArgs("-XX:+HeapDumpOnOutOfMemoryError")
     systemProperty("junit.jupiter.testinstance.lifecycle.default", "per_class")
     val compileTestSnippets = providers.gradleProperty("compile-test-snippets").orNull.toBoolean()
     systemProperty("compile-test-snippets", compileTestSnippets)
```
then `gradlew :detekt-rules-style:test -Pcompile-test-snippets=true`
It starts to trash around `> :detekt-rules-style:test > 785 tests completed` when executing around `UnderscoresInNumericLiteralsSpec`.

The heapdump says the biggest retainers are:
image
`JvmPackagePartProvider` sounds like a good way to start, there's a lot of them:
image
I couldn't figure out what keeps all of these references, because there were a lot of them seemingly active related to the current test (the ones I checked).

Comment (TWiStErRob) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:45]: I tried going with jvisualvm instead of IDEA's analyzer.

This clearly shows the leak:
image

I'm still hitting a wall with not finding what's keeping stuff, so I tried to set up a controlled experiment:
 * Running UnderscoresInNumericLiteralsSpec (a random test)
 * And after that running a test that dumps the heap.
Because the second one should be running after the first has terminated, all the memory used by first should be released. If it's not, hopefully will find a clear indication.
```patch
Subject: [PATCH] helper
---
Index: detekt-rules-style/build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/detekt-rules-style/build.gradle.kts b/detekt-rules-style/build.gradle.kts
--- a/detekt-rules-style/build.gradle.kts	(revision e9e91143261caf02303160723e13de60a7ec1c9d)
+++ b/detekt-rules-style/build.gradle.kts	(date 1675163444659)
@@ -11,3 +11,8 @@
     testImplementation(libs.mockk)
     testImplementation(libs.assertj)
 }
+
+tasks.named<Test>("test") {
+    systemProperty("junit.jupiter.testclass.order.default", "org.junit.jupiter.api.ClassOrderer\$OrderAnnotation")
+    testLogging.events = org.gradle.api.tasks.testing.logging.TestLogEvent.values().toSet()
+}
Index: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnderscoresInNumericLiteralsSpec.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnderscoresInNumericLiteralsSpec.kt b/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnderscoresInNumericLiteralsSpec.kt
--- a/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnderscoresInNumericLiteralsSpec.kt	(revision e9e91143261caf02303160723e13de60a7ec1c9d)
+++ b/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnderscoresInNumericLiteralsSpec.kt	(date 1675162821243)
@@ -6,12 +6,14 @@
 import io.gitlab.arturbosch.detekt.test.lint
 import org.junit.jupiter.api.DisplayName
 import org.junit.jupiter.api.Nested
+import org.junit.jupiter.api.Order
 import org.junit.jupiter.api.Test
 
 private const val ACCEPTABLE_DECIMAL_LENGTH = "acceptableDecimalLength"
 private const val ACCEPTABLE_LENGTH = "acceptableLength"
 private const val ALLOW_NON_STANDARD_GROUPING = "allowNonStandardGrouping"
 
+@Order(1)
 class UnderscoresInNumericLiteralsSpec {
 
     @Nested
Index: detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/HeapDumper.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/HeapDumper.kt b/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/HeapDumper.kt
new file mode 100644
--- /dev/null	(date 1675163194880)
+++ b/detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/HeapDumper.kt	(date 1675163194880)
@@ -0,0 +1,22 @@
+package io.gitlab.arturbosch.detekt.rules.style
+
+import org.junit.jupiter.api.Order
+import org.junit.jupiter.api.Test
+import java.io.File
+
+@Order(2)
+class HeapDumper {
+    @Test fun dump() {
+        repeat(10) { System.gc() }
+        File("heap.hprof").delete()
+        dumpHeap("heap.hprof", true)
+    }
+}
+
+fun dumpHeap(fileName: String, live: Boolean) {
+    java.lang.management.ManagementFactory.newPlatformMXBeanProxy(
+        java.lang.management.ManagementFactory.getPlatformMBeanServer(),
+        "com.sun.management:type=HotSpotDiagnostic",
+        com.sun.management.HotSpotDiagnosticMXBean::class.java
+    ).dumpHeap(fileName, live)
+}
```

```shell
gradlew :detekt-rules-style:test -Pcompile-test-snippets=true --tests="*UnderscoresInNumericLiteralsSpec*" --tests="*HeapDumper*"
```
but this lead me to no discover either. There's a lot of MockProject instances, which suggests that something is leaking, but the only thing holding those objects is the `Disposer`. I tried to debug who's creating them but I only see one creation for the `KtTestCompiler` object.

**Comment by 3flex** [comment]
I didn't intent to push this just yet as there's clearly some clean up to do - however since I did, do you mind testing @VitalyVPinchuk and @TWiStErRob? This is a slightly different approach, but performance seems comparable to the current approach and no longer suffers OOMs. Diagnostics have further improved compared to the "fixed" JSR223 script compiler - the new method picked up additional issues (see fixed tests).

**Comment by TWiStErRob** [comment]
Tomorrow earliest.

**Comment by VitalyVPinchuk** [comment]
Works for me, though the message is now a bit different

**Comment by TWiStErRob** [comment]
Quick repro suggests way better than before.

```shell
gradlew :detekt-rules-style:cleanTest :detekt-rules-style:test --no-build-cache -Pcompile-test-snippets=true
```
e9e91143261caf02303160723e13de60a7ec1c9d -> OOM
078bd93731 -> pass

<details><summary>heap: ok, meta: potential leak (click for charts)</summary>

Memory usages looks way better:
image
However it looks like there might be a slight metaspace leak (I guess all of those tiny classes that are compiled for each test are kept in metaspace):
image

</details>

```shell
gradlew :detekt-rules-coroutines:cleanTest :detekt-rules-coroutines:test --no-build-cache -Pcompile-test-snippets=true
```
e9e91143261caf02303160723e13de60a7ec1c9d + remove `launch` import -> 20 failures
078bd93731 -> 1 failure as expected
But as Vitaly said, the message is different, it doesn't actual tell us what the compile error is in the "usual way":

<details><summary>Before / e9e9114 (click for error message)</summary>

```
SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() FAILED
    io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:21)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)

        Caused by:
        javax.script.ScriptException: Error: error: unresolved reference: launch
            launch {
            ^
        error: suspension functions can be called only within coroutine body
                delay(timeMillis = 1000)
                ^
            at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
            at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
            at io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:45)
            at io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:27)
            ... 3 more
```

</details>

<details><summary>After / 078bd93 (click for error message)</summary>

```
SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() FAILED
    java.lang.RuntimeException: Using JVM IR backend
    Using new faster version of JAR FS: it should make your build faster, but the new implementation is experimental
    Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting
.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rm
i, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.e
d, jdk.internal.le, jdk.internal.opt]
    Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting
.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rm
i, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.e
d, jdk.internal.le, jdk.internal.opt]
    Unresolved reference: launch
    Suspension functions can be called only within coroutine body
        at kotlin.script.experimental.api.ErrorHandlingKt.valueOrThrow(errorHandling.kt:305)
        at io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:71)
        at io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)
```

</details>

**Comment by 3flex** [comment]
The old error is definitely better. But I've spent more time than I wanted to on this already - I can improve the error to remove the warning- and info-level messages, which will help, but the error won't be quite as good as it is now.

Putting that aside, sounds like this fixes the original issue without major drawbacks so I'll tidy this up for merge.

**Comment by TWiStErRob** [comment]
Ok, probably it is possible to find the same diagnostic info somewhere hidden, but agree that it's not in scope here.

What do you think about the metaspace leak? Is there a way to unload the classes compiled dynamically?

File: detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt (hunk 1 above)
Comment (3flex) [reply detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt:23]: I've added a new test in `KotlinScriptEngineTest` - it checks that code with an import compiles, then code with that import missing will fail to compile.

**Comment by 3flex** [comment]
> What do you think about the metaspace leak? Is there a way to unload the classes compiled dynamically?

It looks like you can disable the compiled script cache. Can you try with:

```diff
diff --git a/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt b/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt
index 4115c61027..e5bea9ae5b 100644
--- a/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt
+++ b/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt
@@ -7,6 +7,8 @@ import kotlin.script.experimental.api.isError
 import kotlin.script.experimental.api.onFailure
 import kotlin.script.experimental.host.ScriptingHostConfiguration
 import kotlin.script.experimental.host.toScriptSource
+import kotlin.script.experimental.jvm.CompiledJvmScriptsCache
+import kotlin.script.experimental.jvm.compilationCache
 import kotlin.script.experimental.jvm.jvm
 import kotlin.script.experimental.jvm.updateClasspath
 import kotlin.script.experimental.jvm.util.scriptCompilationClasspathFromContext
@@ -17,7 +19,13 @@ import kotlin.script.experimental.jvmhost.createJvmCompilationConfigurationFromT
  * The object to use the Kotlin script engine for code compilation.
  */
 object KotlinScriptEngine {
-    private val host = BasicJvmScriptingHost(ScriptingHostConfiguration())
+    private val host = BasicJvmScriptingHost(
+        ScriptingHostConfiguration {
+            jvm {
+                compilationCache(CompiledJvmScriptsCache.NoCache)
+            }
+        }
+    )
 
     private val compilationConfiguration = createJvmCompilationConfigurationFromTemplate<MainKtsScript> {
         jvm {
```

If you see good results, I'll add this. If not, let's deal with this if it becomes a problem in a follow up PR.

File: detekt-test-utils/build.gradle.kts [hunk 5]
```diff
@@ -8,8 +8,8 @@ dependencies {
     api(libs.junit.api)
     compileOnly(libs.spek.dsl)
     implementation(projects.detektParser)
-    implementation(libs.kotlin.scriptUtil)
+    implementation(libs.kotlin.mainKts)
+    implementation(libs.kotlinx.coroutines)
```
Comment (BraisGabin) [inline detekt-test-utils/build.gradle.kts:12]: Is the coroutines dependency used? I can't find any usage.

**Review by BraisGabin — COMMENTED** [review]
Even if this PR takes some time to merge we could move the second commit to a new PR and merge it. Those are current errors on our tests and we can merge them to avoid issues and conflicts.

**Comment by 3flex** [comment]
> Even if this PR takes some time to merge

It's just waiting on a review... I have two "works for me" comments above, not sure what else this is waiting on.

If perf turns out to be an issue later we can try disabling the cache as described above but it seems like performance is basically equivalent to what we have today and shouldn't block this from being merged.

File: detekt-test-utils/build.gradle.kts (hunk 5 above)
Comment (3flex) [reply detekt-test-utils/build.gradle.kts:12]: https://github.com/detekt/detekt/blob/3e2cf6b396f1ab40dc1919ec9a183112cd261513/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KtTestCompiler.kt#L4

Coroutines dependency was pulled in transitively through script-util, so since that was removed, it has to be added explicitly.

**Review by BraisGabin — APPROVED** [review]
LGTM. @TWiStErRob did you check if the leak disappears with the patch that 3flex posted?

**Comment by TWiStErRob** [comment]
I just tried https://github.com/detekt/detekt/pull/5741#issuecomment-1420202436, it only makes 4MB (from one sample) difference at the end, but the whole memory profile looks exactly the same. And this gave me an idea (potential explanation): maybe it's not a metaspace leak, it's just loading the test classes as the execution happens, which loads some production classes as well; so it's perfectly normal to see this pattern in a test execution, because each test will only affect a small portion of the code, therefore continuous growth is expected.

**Review by TWiStErRob — APPROVED** [review]
