### PR TITLE
Automatically handle friend paths in JVM compilation analysis tasks

### LINKED ISSUE #3067: Wrong error:  "error: cannot access 'foo': it is internal in 'com.example.bar'"
`internal` in kotlin means it can't be accessed outside the current module.
https://kotlinlang.org/docs/reference/visibility-modifiers.html#modules

In gradle projects, a "module" is a gradle source set, with the exception that the `test` source set can access the internal declarations of `main`

## Expected Behavior
If gradle/kotlinc don't complain about `internal`, then detekt shouldn't complain either.
detekt should match gradle/kotlinc here.

## Observed Behavior
If a `Test` in `/test` accesses a `internal` `foo` extension function defined in `/main`, then detekt complains `error: cannot access 'foo': it is internal in 'com.example.bar'`

## Your Environment

* Version of detekt used: 1.12.0
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: macOS 10.15

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #3067 

Stacks on #7408

Required for #4465

### CODE REVIEW

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/settings/EnvironmentAware.kt [hunk 1]
```diff
@@ -42,11 +44,16 @@ internal class EnvironmentFacade(
...
         )
-        createKotlinCoreEnvironment(
+        val env = createKotlinCoreEnvironment(
             compilerConfiguration,
             disposable,
             printStream,
         )
+
+        val moduleVisibilityManager = ModuleVisibilityManager.SERVICE.getInstance(env.project)
+        compilerConfiguration.getList(JVMConfigurationKeys.FRIEND_PATHS).forEach(moduleVisibilityManager::addFriendPath)
```
Comment (BraisGabin) [inline detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/settings/EnvironmentAware.kt:54]: Nit: you could move this inside an `apply` to set more clear that this is still env configuration? I usually like to use apply for finish the correct construction of an instance.

**Review by BraisGabin — APPROVED** [review]
Tests maybe? On the last 3 PRs you are adding a lot of new features but none of them are tested to avoid regressions.

File: detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/settings/EnvironmentAware.kt (hunk 1 above)
Comment (3flex) [reply detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/settings/EnvironmentAware.kt:54]: Tried this just now but it's the `ModuleVisibilityManager` that's being configured by this line, and using `apply` then only referencing `it` in `forEach` triggered `UnnecessaryApply` so I reverted and left it as is.

Using `apply` on `env` doesn't seem appropriate since it's not actually the `KotlinCoreEnvironment` (env) being configured by these lines. I've left it as is.
