### PR TITLE
UnusedImports rule: fix false negative when same name identifiers are imported and used

### LINKED ISSUE #3020: Unused import not detected
## Expected Behavior

An unused import should be detected.

## Observed Behavior

The unused import is not detected.

## Steps to Reproduce

When using [clikt](https://github.com/ajalt/clikt), import

```
import com.github.ajalt.clikt.parameters.arguments.convert
import com.github.ajalt.clikt.parameters.options.convert
```

but use only `com.github.ajalt.clikt.parameters.arguments.convert`, then `com.github.ajalt.clikt.parameters.options.convert` is not detected as an unused import.

## Context

See https://github.com/oss-review-toolkit/ort/blob/376555874ab7e46a95e894a2702e15b94326ee85/helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt#L24-L25

## Your Environment

* Version of detekt used: 1.12.0
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/oss-review-toolkit/ort

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #3020

### CODE REVIEW

**Review by schalkms — APPROVED** [review]

**Review by arturbosch — APPROVED** [review]

File: detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedImports.kt [hunk 1]
```diff
@@ -53,17 +58,31 @@ class UnusedImports(config: Config) : Rule(config) {
...
 
-            fun KtImportDirective.isNotUsed() =
-                    aliasName !in namedReferences && identifier() !in namedReferences
+            @Suppress("ReturnCount")
+            fun KtImportDirective.isNotUsed(): Boolean {
+                val namedReferencesAsString = namedReferences.map { it.text.trim('`') }
+                if (aliasName in (namedReferencesInKDoc + namedReferencesAsString)) return false
+                val identifier = identifier()
+                if (identifier in namedReferencesInKDoc) return false
+                return if (bindingContext == BindingContext.EMPTY) {
```
Comment (cortinico) [inline detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnusedImports.kt:77]: This is yet another rule where we're adding a mixed behavior based on Type Resolution: #2994 

Ideally we should either:
- Restrict this rule to work on TR only or 
- Remove the `@requiresTypeResolution` in the documentation as it's an overstatement
- Revert this change and find a different solution that doesn't require TR.
