### PR TITLE
RequireTypeResolution now is an interface instead of an annotation

### LINKED ISSUE #7492: Ensure that all the rules define correctly if they need type solving/full mode
## Expected Behavior
It's easy to find out if your rule is missing the requires type solving annotation. 

## Current Behavior
Right now it's really difficult to know that. We have a rule to detect it but it's not bullet proof. 

A solution for this would be that the get of the property `bindingContext` in the rule will crash at any attempt to read its value if the rule doesn't have the annotation. To be clear, I'm talking about the behavior here. We doesn't need to check that for each read.

There is another solution: change the annotation to an interface. The rule will not have a `bindingContext` property. The interface will have that property. This way you would find out this limitation at compilation time instead of run time. Also this will avoid to use reflection to check if the rule has or not an annotation (now I'm talking at the `detrkt-core` level). A simple `is` will work. The downside is that we lose discoberability. With the first solution, a user with little experience will find the `bindingContext`. S/he will see an exception telling her/him to add the annotation as soon as the code is executed. With this solution you need to read documentation to find out that there is a magic annotation that gives you access to the `bindingContext`.

### PR DESCRIPTION
**Pull request by BraisGabin**
Closes #7492

For full context please read the linked issue.

### CODE REVIEW

File: config/detekt/argsfile [hunk 1]
```diff
@@ -17,3 +17,4 @@ txt:./build/detekt-report.txt
 sarif:./build/detekt-report.sarif
 -bp
 .
+--auto-correct
```
Comment (cortinico) [inline config/detekt/argsfile:20]: Why this?

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt [hunk 2]
```diff
@@ -1,11 +1,7 @@
...
- * The detekt core will honor this annotation and it will not run any rule with this annotation if the bindingContext
- * is empty.
- */
-@Target(AnnotationTarget.CLASS)
-@Retention(AnnotationRetention.RUNTIME)
-annotation class RequiresTypeResolution
+import org.jetbrains.kotlin.resolve.BindingContext
+
+interface RequiresTypeResolution {
+    var bindingContext: BindingContext
```
Comment (cortinico) [inline detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt:6]: How do you feel about moving this to a `val` and instead of letting users use `lateinit` var do something like this:

```
override val bindingContext: BindingContext by lazy { bindingContextProvider() }
```

The `bindingContextProvider` can then be a function inside the `Rule` class with a field that we populate before we `visitFile`, only if the rule implements `RequiresTypeResolution`

File: config/detekt/argsfile (hunk 1 above)
Comment (BraisGabin) [reply config/detekt/argsfile:20]: My bad. This shouldn't be committed.

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt (hunk 2 above)
Comment (BraisGabin) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: I didn't implement exactly your idea but this solution doesn't need `lateinit var` either.

The problem of this solution is that it's not that clear that if you implements `RequiresTypeSolving` you will get access to `bindingContext`.

Comment (cortinico) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: Yeah I see. Still a step in the right direction rather than `var bindingContext`. Curious to hear what other thinks about this

Comment (BraisGabin) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: I also tried your option with 
```kotlin
override val bindingContext: BindingContext by lazy { bindingContextProvider() }
```

The problem is that anyone could use `bindingContextProvider()` without implementing `RequiresTypeResolution` and that would break the main idea behind this PR.

Comment (cortinico) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: > without implementing RequiresTypeResolution and that would break the main idea behind this PR.

We won't be populating the backing field of that function though no? So calling `bindingContextProvider()` on a Rule that does not implement `RequiresTypeResolution` results in a crash.

File: detekt-rules-coroutines/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/RedundantSuspendModifier.kt [hunk 3]
```diff
@@ -52,13 +52,13 @@ import org.jetbrains.kotlin.resolve.descriptorUtil.fqNameSafe
...
-    config,
-    "The `suspend` modifier is only needed for functions that contain suspending calls."
-) {
-
+class RedundantSuspendModifier(config: Config) :
+    Rule(
+        config,
+        "The `suspend` modifier is only needed for functions that contain suspending calls."
+    ),
+    RequiresTypeResolution {
```
Comment (3flex) [inline detekt-rules-coroutines/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/RedundantSuspendModifier.kt:61]: nit: Should have a blank line between opening brace and class body, or put opening brace in its own line (see the last couple of examples here: https://kotlinlang.org/docs/coding-conventions.html#class-headers)

This prompted a request for a rule enforcing this in ktlint.

It's not a must to adjust in this PR but it looked a bit off so did some sleuthing for recommendations.

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt [hunk 4]
```diff
@@ -1,11 +1,3 @@
 package io.gitlab.arturbosch.detekt.api
 
-/**
- * Annotated [Rule] requires type resolution to work.
- *
- * The detekt core will honor this annotation and it will not run any rule with this annotation if the bindingContext
- * is empty.
- */
```
Comment (3flex) [inline detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt:8]: We should keep some documentation here.

**Comment by BraisGabin** [comment]
I'll address the comments soon but I'm moving it to draft as this is clearly not ready yet to be merge.

File: detekt-rules-coroutines/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/RedundantSuspendModifier.kt (hunk 3 above)
Comment (BraisGabin) [reply detekt-rules-coroutines/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/RedundantSuspendModifier.kt]: Fixed

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt (hunk 4 above)
Comment (BraisGabin) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: Done

File: detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt (hunk 2 above)
Comment (BraisGabin) [reply detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/RequiresTypeResolution.kt]: What do you think about the current implementation? I think that it have the good parts of both sides. To read the `contextBinding` you need to be inside the context of `RequiresFullAnalysis`. So you need to implement `RequiresFullAnalysis` to access it (or do really odd tricks like `with(object : RequiresFullAnalysis {}) { contextBinding }` that will compile but will crash.

I think that this option keeps the type safety without forcing the rules to have any new `var`

**Comment by BraisGabin** [comment]
I fixed the conflicts (there were a ton) and the comments. It is ready to review again :)

**Review by cortinico — APPROVED** [review]
I haven't checked each rule one by one, but the code inside core looks legit 👍

**Comment by cortinico** [comment]
This is awesome btw :)
