### PR TITLE
Reproduce/Fix error during snippet compilation

### LINKED ISSUE #4535: Unable to compile code snippets with `KotlinScriptEngine` repeatedly
related to [work on the migration to junit](https://github.com/detekt/detekt/pull/4523#issuecomment-1021062680).

## Observed Behavior
Running all tests with snippet compilation fails with a compiler exception.

```
IgnoredReturnValueSpec > default config with annotated return values > does not report when a function's return value is used in a test statement() FAILED
    org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_18
    File being compiled: (2,35) in /Line_18.kts
    The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:43)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:457)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitScript(KtVisitor.java:78)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:523)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
        at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.registerDeclarations(LazyTopDownAnalyzer.kt:80)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitKtFile(LazyTopDownAnalyzer.kt:98)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:517)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:245)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:232)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitElement(ExceptionWrappingKtVisitorVoid.kt:27)
        at app//org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:517)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:245)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:232)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:203)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.runAnalyzer(ReplCodeAnalyzer.kt:127)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.doAnalyze(ReplCodeAnalyzer.kt:136)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.analyzeReplLine(ReplCodeAnalyzer.kt:109)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.GenericReplCompiler.compile(GenericReplCompiler.kt:81)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:72)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:18)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:60)
        at app//io.gitlab.arturbosch.detekt.rules.bugs.IgnoredReturnValueSpec$default config with annotated return values.does not report when a function's return value is used in a test statement(IgnoredReturnValueSpec.kt:436)

        Caused by:
        org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration SCRIPT
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:17)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.findClassDescriptor(LazyDeclarationResolver.kt:88)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.getScriptDescriptor(LazyDeclarationResolver.kt:65)
            at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitScript(LazyTopDownAnalyzer.kt:91)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:523)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
            at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
            at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
            at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:32)
            ... 33 more
```
## Steps to Reproduce
`./gradlew test -x :detekt-gradle-plugin:test -Pcompile-test-snippets=true --rerun-tasks`.

### PR DESCRIPTION
**Pull request by marschwar**
This closes #4535

### CODE REVIEW

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt [hunk 1]
```diff
@@ -14,11 +18,25 @@ object KotlinScriptEngine {
...
         try {
-            KotlinScriptEnginePool.getEngine().compile(code)
+            compile(code)
+        } catch (_: KotlinFrontEndException) {
+            println(
+                "Kotlin compiler exception detected. " +
+                    "This could be caused by a name clash with previously compiled snippets. Will retry to compile" +
+                    "\n$code\n" +
+                    "with a fresh script engine."
+            )
```
Comment (BraisGabin) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt:34]: This could make our tests really verbose, right? Wouldn't it be better to remove it?

**Review by BraisGabin — APPROVED** [review]

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt (hunk 1 above)
Comment (cortinico) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt:34]: Agree. Maybe just print a oneliner like:
```
w: Kotlin compiler exception detected at <file:loc>
```

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt [hunk 2]
```diff
@@ -3,35 +3,35 @@ package io.github.detekt.test.utils
...
+import java.util.Collections
 
 /**
  * The object to manage a pool of Kotlin script engines to distribute the load for compiling code.
  * The load for compiling code is distributed over a number of engines.
  */
 internal object KotlinScriptEnginePool {
 
-    private const val NUMBER_OF_ENGINES = 8
+    private val AVAILABLE_ENGINES: MutableList<PooledScriptEngine> =
```
Comment (cortinico) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:14]: Please add a comment somewhere, as it's not immediately clear to the reader why this is needed.

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt (hunk 1 above)
Comment (marschwar) [reply detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEngine.kt:34]: I see your point. The only thing I would argue against it is, that by printing the snippet we have a chance to fix the root cause increasing the build speed in the process. But since this is done in the CI only, this will most likely not happen. I will change it to a one liner.

**Review by cortinico — APPROVED** [review]

File: detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt [hunk 3]
```diff
@@ -3,35 +3,50 @@ package io.github.detekt.test.utils
...
  * The object to manage a pool of Kotlin script engines to distribute the load for compiling code.
- * The load for compiling code is distributed over a number of engines.
+ * Creating script engines is expensive so they are reused when compiling snippets. The pool is able to grow
+ * dynamically so whenever there is no script engine available, a new one is created. Access to the pooled engines is
+ * thread safe.
  */
 internal object KotlinScriptEnginePool {
 
-    private const val NUMBER_OF_ENGINES = 8
+    private val AVAILABLE_ENGINES: MutableList<PooledScriptEngine> =
```
Comment (chao2zhang) [inline detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt:16]: Styling: Could we use camelCase for this property since this is no longer a constant.

File: detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+
+        val validCode = """
+            package pooled.c
+            
+            class A
+        """.trimIndent()
+
+        val engine = KotlinScriptEnginePool.borrowEngine()
+
+        assertThatThrownBy { engine.compile(invalidCode) }
```
Comment (chao2zhang) [inline detekt-test-utils/src/test/kotlin/io/github/detekt/test/utils/PooledScriptEngineTest.kt:51]:
```suggestion
        assertThatThrownBy { engine.compile(invalidCode) }
            .isInstanceOf(ScriptException::class.java)
```

**Review by chao2zhang — APPROVED** [review]

**Comment by BraisGabin** [comment]
Captura de pantalla 2022-02-01 a las 9 12 03

Just by running `./gradlew test` those warnings appear. I vote for removing them.

And as a side note, would it have sense now to reduce the "repat" to `2`? It will increase the test speed and it would test the same.
