### PR TITLE
Kotlin 2.2.20

### LINKED ISSUE #8670: UnnecessaryParentheses fails with kotlin 2.2.20: ClassNotFoundException: org.jetbrains.kotlin.parsing.KotlinExpressionParsing$Precedence
## Expected Behavior

detekt should be able to run with a minor upgrade of kotlin version

## Observed Behavior

```
[INFO]    [detekt] Location: io.gitlab.arturbosch.detekt.rules.style.UnnecessaryParentheses.<clinit>(UnnecessaryParentheses.kt:97)
[INFO]    [detekt] The original exception message was: org/jetbrains/kotlin/parsing/KotlinExpressionParsing$Precedence
[INFO]    [detekt] Running detekt '1.23.8' on Java '21.0.5+11-Ubuntu-1ubuntu122.04' on OS 'Linux'
[INFO]    [detekt] If the exception message does not help, please feel free to create an issue on our GitHub page.
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.AnalyzerKt.throwIllegalStateException(Analyzer.kt:185)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.AnalyzerKt.access$throwIllegalStateException(Analyzer.kt:1)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:75)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.Analyzer.run(Analyzer.kt:53)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze$lambda$6(Lifecycle.kt:47)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:43)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:34)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:44)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:61)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$lambda$8(AnalysisFacade.kt:48)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:47)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:31)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:14)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:20)
[INFO]    [detekt] Caused by: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/parsing/KotlinExpressionParsing$Precedence
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.rules.style.UnnecessaryParentheses.<clinit>(UnnecessaryParentheses.kt:97)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.rules.style.StyleGuideProvider.instance(StyleGuideProvider.kt:52)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.Analyzer.analyze$lambda$13(Analyzer.kt:113)
[INFO]    [detekt]      at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:243)
[INFO]    [detekt]      at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:203)
[INFO]    [detekt]      at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:227)
[INFO]    [detekt]      at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:247)
[INFO]    [detekt]      at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:361)
[INFO]    [detekt]      at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:351)
[INFO]    [detekt]      at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:449)
[INFO]    [detekt]      at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:617)
[INFO]    [detekt]      at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:611)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.rules.RuleSetsKt.associateRuleIdsToRuleSetIds(RuleSets.kt:51)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:116)
[INFO]    [detekt]      at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:74)
[INFO]    [detekt]      ... 14 more
[INFO]    [detekt] Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.parsing.KotlinExpressionParsing$Precedence
[INFO]    [detekt]      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[INFO]    [detekt]      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[INFO]    [detekt]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[INFO]    [detekt]      ... 29 more
```
## Steps to Reproduce

bump kotlin dependency from 2.2.10 to 2.2.20

## Context

(I can keep 2.2.10 for the antrun/detekt plugin dependency but prefer to have one version of things across the project)

## Your Environment

* Version of detekt used: 1.23.8
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository): https://github.com/josephlbarnett/leakycauldron/blob/main/parent-pom/pom.xml#L1232-L1327

### LINKED ISSUE #8714: Java 25 unsupported on v1.23.8
## Expected Behavior

Detekt should run under a Java 25 JVM with a JVM target of 17.

## Observed Behavior

Execution fails with an error of:

```
Caused by: java.lang.IllegalArgumentException: 25
        at org.jetbrains.kotlin.com.intellij.util.lang.JavaVersion.parse(JavaVersion.java:307)
        at org.jetbrains.kotlin.com.intellij.util.lang.JavaVersion.current(JavaVersion.java:176)
        at org.jetbrains.kotlin.cli.jvm.modules.JavaVersionUtilsKt.isAtLeastJava9(javaVersionUtils.kt:11)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem.globalJrtFsCache$lambda$2(CoreJrtFileSystem.kt:83)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem.globalJrtFsCache$lambda$3(CoreJrtFileSystem.kt:74)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem.roots$lambda$0(CoreJrtFileSystem.kt:34)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem.roots$lambda$1(CoreJrtFileSystem.kt:33)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem.findFileByPath(CoreJrtFileSystem.kt:42)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.<init>(CliJavaModuleFinder.kt:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:243)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:468)
        at io.github.detekt.parser.KotlinEnvironmentUtilsKt.createKotlinCoreEnvironment(KotlinEnvironmentUtils.kt:61)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade.environment_delegate$lambda$0(EnvironmentAware.kt:45)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade.getEnvironment(EnvironmentAware.kt:35)
        at io.gitlab.arturbosch.detekt.core.ProcessingSettings.getEnvironment(ProcessingSettings.kt)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:18)
        at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt.inputPathsToKtFiles$lambda$2(ParsingStrategy.kt:24)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze$lambda$1(Lifecycle.kt:38)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:34)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:38)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:61)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$lambda$8(AnalysisFacade.kt:48)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:47)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
        ... 125 more
```

## Steps to Reproduce

Define Detekt config via Gradle like so:

```
detekt {
    buildUponDefaultConfig = true
}
tasks.withType<Detekt>().configureEach {
    jvmTarget = "17"
    reports {
        sarif.required = true
    }
}
```

1. Install Corretto 25
2. Run `./gradlew check`

## Context

It appears that this is a flaw within the Kotlin compiler that [was fixed in v2.1.20](https://github.com/JetBrains/kotlin/commit/e0bf708be3f9dbbc5e6671ecabad88196d4a10ca). It hardcoded a less-than-25 when parsing a Java version, and 25 > (25 - 1).

https://github.com/detekt/detekt/pull/8302 will fix it, but hopefully that's backported to Detekt v1? 🤞 

## Your Environment

* Version of detekt used: v1.23.8
* Version of Gradle used (if applicable): v9.1.0 + Corretto 25
* Gradle scan link (add `--scan` option when running the gradle task): n/a
* Operating System and version: macOS Tahoe
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #8670
Fixes #8714

### CODE REVIEW

**Comment by Goooler** [comment]
We can include BCV migration into this PR, like https://github.com/GradleUp/shadow/pull/1481.

**Comment by yesitskev** [comment]
It's unwise to target an RC version of Kotlin.

**Comment by BraisGabin** [comment]
> It's unwise to target an RC version of Kotlin.

It's a really good way to be ready as fast as possible for the next stable release. This PR will never be merged like this. It's just a WIP to be prepared for the stable.

**Comment by cortinico** [comment]
This should also fix https://github.com/detekt/detekt/pull/8714 as mentioend by @rgrochowicz

EDIT: typo

**Comment by 3flex** [comment]
> This should also fix https://github.com/detekt/detekt/pull/8302

Assume that's #8714?

**Comment by cortinico** [comment]
> Assume that's #8714?

Indeed 👍

File: detekt-rules-style/src/main/kotlin/dev/detekt/rules/style/UnnecessaryParentheses.kt [hunk 1]
```diff
@@ -83,41 +83,41 @@ class UnnecessaryParentheses(config: Config) : Rule(
...
+                BinaryOperationPrecedence.EQUALITY, // (a ?: b) == c
+                BinaryOperationPrecedence.COMPARISON, // (a ?: b) > c
+                BinaryOperationPrecedence.IN_OR_IS, // (a ?: b) in c
             ),
-            Precedence.SIMPLE_NAME to arrayOf(
-                Precedence.ELVIS, // a ?: (b to c)
-                Precedence.SIMPLE_NAME, // (a to b) to c
+            BinaryOperationPrecedence.INFIX to arrayOf(
+                BinaryOperationPrecedence.ELVIS, // a ?: (b to c)
+                BinaryOperationPrecedence.INFIX, // (a to b) to c
```
Comment (3flex) [inline detekt-rules-style/src/main/kotlin/dev/detekt/rules/style/UnnecessaryParentheses.kt:98]: The semantics may have changed here - `SIMPLE_NAME` was the only enum value that didn't have a direct equivalent in `BinaryOperationPrecedence`.

I'm relying on test coverage, which may not be sufficient, but I spent WAY too much time on this PR working through the required changes so unless anyone can point out that this is definitely wrong and provide a fix I will leave things as they are and fixes can follow in other PRs.
